### ISSUE TITLE
libbitcoin compile error

### ISSUE THREAD

**Issue by potadibyo** [libbitcoin/libbitcoin#1008]
*libbitcoin_util.a(libbitcoin_util_a-util.o): In function

CInit::CInit()': /root/mrcash/src/util.cpp:133: undefined reference to

OPENSSL_init_crypto'
collect2: error: ld returned 1 exit status
Makefile:3661: recipe for target 'mrcashd' failed
make[2]: * mrcashd] Error 1
make[2]: Leaving directory '/root/mrcash/src'
Makefile:9359: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/mrcash/src'
Makefile:741: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
Please help me to solve that problem.......

**Comment by thecodefactory** [comment]
@potadibyo This appears to be a problem with bitcoin core (or some repo derived from there), which internally builds libraries such as libbitcoin_util.  Are you trying to build with the libbitcoin project repos instead?
