### ISSUE TITLE
OP_IF/NOTIF argument must be minimal

### ISSUE THREAD

**Issue by rotoava** [libbitcoin/libbitcoin#1041]
**Issue**

I use `bx validate-tx` to validate TX data. Some TX show `The transaction is valid` according by bx, but when I submit it to a Bitcoincore node, shows error `OP_IF/NOTIF argument must be minimal` .

So maybe this `MINIMALIF` feature is missed.

**Related Information**

BIP141: [The argument of OP_IF/NOTIF in P2WSH must be minimal](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki) 

BitcoinCore code: [return set_error(serror, SCRIPT_ERR_MINIMALIF)](https://github.com/bitcoin/bitcoin/blob/78dae8caccd82cfbfd76557f1fb7d7557c7b5edb/src/script/interpreter.cpp#L482)

I'm not familiar with C++ code, so I can't dig the code or submit PR.
Thanks to this great tool, this is the only tool that can verify raw TX and avoid broadcasting directly.

**Comment by evoskuil** [comment]
Minimal if is a policy applied by some nodes, not a consensus rule. Non-minimal if is valid, always, there is no missing feature:

```
Three  **relay and mining policies** are also included in the first release of segregated witness [...]

Only compressed public keys are accepted in P2WPKH and P2WSH (See BIP143)
The argument of OP_IF/NOTIF in P2WSH must be minimal[4]
Signature(s) must be null vector(s) if an OP_CHECKSIG or OP_CHECKMULTISIG is failed (for both pre-segregated witness script and P2WSH. See BIP146)
```

If you want to conform to this policy, simply make transactions that do so.

**Comment by evoskuil** [comment]
> Thanks to this great tool, this is the only tool that can verify raw TX and avoid broadcasting directly.

Thanks for the feedback.
