### ISSUE TITLE
Divide dictionary into multiple source files.

### ISSUE THREAD

**Issue by ldz1** [libbitcoin/libbitcoin#1066]
Hi. The dictionary file is extremely large (>20000 lines). It can be several times larger if new languages appear. For readability, clarity and extensibility I would like to suggest dividing the file into individual languages.

**Comment by thecodefactory** [comment]
@ldz1 I'm looking at dictionary related issues, so I'll take this one unless you've got it going already.

**Comment by ldz1** [comment]
@thecodefactory It's OK. I haven't started this task :).
