### ISSUE TITLE
Segwit activation does not work on regtest

### ISSUE THREAD

**Issue by baiumbg** [libbitcoin/libbitcoin#1077]
This can be reproduced by adding a bitcoind (v0.16+) peer to a libbitcoin-server instance on regtest. 

As soon as libbitcoin-server attempts to index a block received through the bitcoind instance, it throws a `[node] Rejected block [block_hash] from [localhost:port] transaction inputs or outputs empty` message. This indicates to me that segwit does not get activated properly on regtest, since segwit was enabled from block 0 in the satoshi client (as of v0.16.0).

The same error is thrown with an earlier version of bitcoind, but at block height 432, which is when the activation occurred in previous versions.

**Comment by evoskuil** [comment]
See: https://github.com/libbitcoin/libbitcoin/pull/1076

Thanks!
