### ISSUE TITLE
Partially Signed Bitcoin Transactions (PSBT BIP-174)

### ISSUE THREAD

**Issue by ChristopherA** [libbitcoin/libbitcoin#1082]
Any plans on roadmap to support Partially Signed Bitcoin Transactions (PSBT BIP-174)?

**Comment by thecodefactory** [comment]
Pull requests welcomed!

**Comment by evoskuil** [comment]
It's not on the v4 roadmap, but as @thecodefactory sais, pull requests are always welcome.

Closing as resolved.
