### ISSUE TITLE
Roadmap at Woefully Out-Of-Date

### ISSUE THREAD

**Issue by ChristopherA** [libbitcoin/libbitcoin#1084]
Was told in https://github.com/libbitcoin/libbitcoin/issues/1083 & https://github.com/libbitcoin/libbitcoin/issues/1082 that these features are not in the version 4 roadmap, but the roadmap(s) at http://libbitcoin.github.io/roadmap.html & https://libbitcoin.dyne.org/roadmap.html are woefully out-of-date, pointing to 1.8.

Where is the new roadmap with .4?

**Comment by evoskuil** [comment]
That site is entirely out of date and unrelated to modern libbitcoin work. We don’t take issues against it here ;). Features for v4 are pending in the github issues lists and associated with v4.

**Comment by evoskuil** [comment]
Resolved.
