### ISSUE TITLE
RFC 6979 implementation does not check for valid r or s.

### ISSUE THREAD

**Issue by bip32JP** [libbitcoin/libbitcoin#166]
https://github.com/libbitcoin/libbitcoin/blob/version2/src/math/ec_keys.cpp#L131

Currently the only requirement for a valid k is `secp256k1_ec_seckey_verify == 1` which only checks the validity of k itself (that it is in bounds)

However RFC6979 states:

> If that value of k is within the [1,q-1] range, and **is
> suitable for DSA or ECDSA (i.e., it results in an r value
> that is not 0**; see Section 3.4), then the generation of k is
> finished.  The obtained value of k is used in DSA or ECDSA.
> **Otherwise, compute**:

So while r == 0 or s == 0 is a highly unlikely occurrence, we must account for it to stay rfc 6979 compliant.

For instance, bitcore uses an int called `badrs` and increments it if there is a bad r or s.
https://github.com/bitpay/bitcore/blob/master/lib/crypto/ecdsa.js#L208

This badrs is accounted for in the deterministicK() and forces a loop of Step H for each iteration that generated a bad r or s value.
https://github.com/bitpay/bitcore/blob/master/lib/crypto/ecdsa.js#L100

**Comment by swansontec** [comment]
Thanks for looking at this! I am glad to see that somebody is auditing the crypto code.

While I did see that requirement in the RFC, I figured the odds were low enough not to make a difference. I am not alone in this, since the [python-ecdsa](https://github.com/warner/python-ecdsa/blob/master/ecdsa/rfc6979.py) implementation makes a similar omission. Still, if people think this is important, I can add another optional parameter to the `create_nonce` function which one can increment each time `sign` fails.

**Comment by bip32JP** [comment]
I added a similar issue to python-ecdsa.

The only reason I bring this up is that recent pushes (since the blockchain.info debacle) for RFC 6979 has caused me to research the current state of implementation in the bitcoin space.

I found that most commonly:
1. implementations are almost 100% (with exception being python-ecdsa) under the assumption of secp256k1. (assuming hlen == qlen, and the length of the hmac == tlen (so no looping for T = T || V)
2. r == 0 and s == 0 cases are almost 100% delegated to throwing errors. (with the exception of bitcore)
3. Some implementations don't even check for out of bounds k before returning the k. (breadwallet) or just throw errors (cyptocoin elliptic libraries)

(1 may not be a huge problem if we assume bitcoin will never change curves... however, bitcoin changing curves seems more probable than r == 0 or s == 0 case imo...)

but considering this library holds the secp256k1 library as a main pillar, I think 1 is ok to leave as is.

3 is fine already

2 should be dealt with if it can be done in a fashion that does not complicate the code base too much.

breadwallet told me that they would check for out of bounds k, but leave r or s == 0 to throw an error and prevent signing.

> I can add another optional parameter to the create_nonce function which one can increment each time sign fails.

This is how bitcore handles it. If it doesn't complicate things too much.

Not to mention bitcore's badrs method is helpful in that you can then force the extra failure loops by modifying badrs manually. I have made test cases for badrs values of 1 and 15 along with 0 failure badrs = 0 values.

These test cases and an explanation of the caveat to them are at this issue:
https://github.com/bitcoinjs/bitcoinjs-lib/pull/337#issuecomment-68620793

**Comment by swansontec** [comment]
Thanks for the run-down. We can address issue (1) if and when Bitcoin ever does switch to another signature scheme. I'll go ahead and fix issue (2) properly, so we just keep trying new nonces until we get one that works.

**Comment by bip32JP** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/pull/337/files

@dcousens made a javascript version that retains r and s from the check to use after the deterministicK function is run.

I'm sure C++ will be able to do something similar in a fairly concise manner...

(I should really start learning C++ so I can look over bitcoin/bitcoin)

**Comment by swansontec** [comment]
Please look over pull request #170. It should solve the problem completely and thouroughly, at least when using the newly-added deterministic `sign` functions. I've removed the out-of-bounds check from `create_nonce`, since the `sign` function already checks for this, along with invalid r and s values. Thus, the caveat with your unit test does not apply here.

**Comment by evoskuil** [comment]
Resolved.
