### ISSUE TITLE
Boost libraries missing from libbitcoin.pc

### ISSUE THREAD

**Issue by swansontec** [libbitcoin/libbitcoin#213]
The installed `libbitcoin.pc` file doesn't include any `-lboost*` flags, which means that anybody using the pkg-config system to link libbitcoin (including the downstream libbitcoin-blockchain and friends) are bound to have linker problems. Indeed, I am unable to build the server stack at this point.

A git blame shows that commit 2a8db6ca introduced this problem. The `@boost_LIBS@` substitution doesn't include anything other than the `-L` directory flag. To get the linker flags, `libbitcoin.pc.in` file should include substitutions like `@boost_system_LIBS@` for each Boost library in use.

**Comment by evoskuil** [comment]
Sorry, this is a regression from a work in progress. The plan is to introduce the individual boost linker flags in the package config as you describe. I'll fix up soon.

**Comment by swansontec** [comment]
Indeed, editing `libbitcoin.pc.in` like so has fixed the issue:

    Libs: -L${libdir} -lbitcoin -lpthread @boost_LIBS@ @boost_system_LIBS@ @boost_datime_LIBS@ @boost_filesystem_LIBS@ @boost_locale_LIBS@ @boost_program_options @boost_regex_LIBS@ @rt_LIBS@

Since this file comes from [your build generator](libbitcoin/libbitcoin-build), I imagine the problem will need to be fixed over there.

**Comment by evoskuil** [comment]
Yes, I inadvertently checked in the new generated Makefile.am without the corresponding updates to the package config. I was maintaining those changes manually in the interim, but missed it on that commit.

**Comment by evoskuil** [comment]
Fixed in https://github.com/libbitcoin/libbitcoin/commit/b6edf73a8a2b50b0040370f5a6a88248d739961b, not yet merged to version2.
