### ISSUE TITLE
ios - linker error

### ISSUE THREAD

**Issue by rhabal** [libbitcoin/libbitcoin#244]
I successfully managed to compile / link the airbitz stuff (great project!). But I have a linker error.

But for one of my objects that I used to use w the raw libbitcoin (on Mac), it no longer works on iOS. I am getting this failure below.  Commenting the encode_hex method out solves it. Please note I am doing the universal-ios build:

Undefined symbols for architecture x86_64:
  "libbitcoin::encode_hex(libbitcoin::array_slice<unsigned char>)", referenced from:
      Wrapper::MainLoop() in Wrapper.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thanks

**Comment by evoskuil** [comment]
The implementation of the function is here: https://github.com/libbitcoin/libbitcoin/blob/master/src/formats/base16.cpp#L107

Notice however that there is no `array_slice` in the libbitcoin namespace.

**Comment by evoskuil** [comment]
Can we close this?
