### ISSUE TITLE
ec_keys is not thread safe

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin#245]
https://github.com/evoskuil/libbitcoin/blob/master/src/math/ec_keys.cpp#L62

**Comment by swansontec** [comment]
Just add a `std::mutex mutex_` member to the init_singleton class, and lock it with `std::lock_guard<std::mutex> lock(mutex_);` inside `init_singleton::init()`, and things should be safe

**Comment by evoskuil** [comment]
Resolved.
