### ISSUE TITLE
install.sh and --enable-testnet

### ISSUE THREAD

**Issue by venzen** [libbitcoin/libbitcoin#263]
I'm using the _./install.sh_ script to install but it does not recognize the **--enable-testnet** option suggested in the _README_, although the _.travis.yml_ file refers to it.

Did something change?

**Comment by evoskuil** [comment]
What is your indication that it's not recognized?

**Comment by venzen** [comment]
hi, 

in latest latest master branch:

$ sudo ./install.sh --enable-testnet
...[snip]..
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
configure: --enable-testnet --disable-tests
**configure: WARNING: unrecognized options: --enable-testnet**
checking build system type... x86_64-unknown-linux-gnu
...[snip]...

The warning shows again later during the build, at which time I aborted.

**Comment by evoskuil** [comment]
If this is showing in the `libsecp256k1` build then it's expected. The installer passes most options (it strips its own options) to each build and this option isn't relevant to that build. It's standard behavior for autotools to ignore unsupported options so that this technique can be used.

**Comment by venzen** [comment]
I should probably have let the build complete, seeing that this is a warning and not an error, and attempted connection to testnet.

Thanks for explaining, @evoskuil

**Comment by venzen** [comment]
For the record, build completes on Lubuntu 14.04 with tests passed:

============================================================================
Testsuite summary for libbitcoin 2.9.0
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
