### ISSUE TITLE
Isuuse with Linux build for this library

### ISSUE THREAD

**Issue by ramkumarkoppu** [libbitcoin/libbitcoin#267]
checking for boostlib >= 1.55.0... configure: We could not detect the boost libraries (version 1.55 or higher). If you have a staged boost library (still not installed) please specify $BOOST_ROOT in your environment and do not give a PATH to --with-boost option.  If you are sure you have boost installed, then check your version number looking in <boost/version.hpp>. See http://randspringer.de/boost for more documentation.
configure: error: Boost 1.55.0 or later is required but was not found.

**Comment by thecodefactory** [comment]
Are you using the install.sh script?  It will take care of the dependencies for you.  If you already have the dependencies configured on your system, you can use autogen.sh/configure/make/etc.
