### ISSUE TITLE
Create API to expose version for each library.

### ISSUE THREAD

**Issue by mlmikael** [libbitcoin/libbitcoin#275]
For the application to know at runtime which version of LibBitcoin it's actually linked to, a procedure or method to get the
- The LibBitcoin release number (as in, 203 = v2.03),
- Git commit number if possible, and
- String presentation ("LibBitcoin Node v2.03 abc01234"),

would be perfect.

(Just including this in headers e.g. "#define libbitcoin_version 203") would _not_ suffice as the shared library file is picked by the OS dynamic library loader at proram load time, and may differ from the libbitcoin version for which headers were installed at compile time.)

**Comment by evoskuil** [comment]
If the shared (or static) library that is linked is not of the same version that was reverenced by the dependent library  (via headers) you would in most cases encounter a linking error. However in the case where you do not it still constitutes a broken build.

There are other dependencies that could be incorrectly linked, such as boost (I've seen this), ICU openssl, sodium, zmq/czmq/czmqpp. This guard will not work with them. This is the purpose of the version-checking in pkg-config. Although it's not perfect I don't believe that such guards at runtime are appropriate. Again, this is the whole point of library versioning.

We do have command line options in bx and bs that emit (libbitcoin-only) dependency version information (and the testnet flag). But of course these presume correct linkage.

We don't version intermediate changes (i.e. the release branches are versioned when breaking change or new feature is introduced, master is changing without version updates). This is a developer vs. end-user differentiation. Given the granularity you are after, you are suggesting this change to aid developers.

Finally, automatically integrating git information into the sources as they are checked in is a non-trivial integration problem. Doing it manually wouldn't be reliable.

**Comment by mlmikael** [comment]
OpenSSL exports SSLeay_version(SSLEAY_VERSION) https://www.openssl.org/docs/crypto/OPENSSL_VERSION_NUMBER.html and SQLite exports sqlite3_libversion() and sqlite3_libversion_number(): https://www.sqlite.org/capi3ref.html#sqlite3_libversion .

What about something like that?

(GIT commit number nontrivial - ok good idea to drop it then. But, I guess the fact that very mainstream libraries such as the abovementioned export version numbers at runtime, should mean that that as a convention has been found to be useful.
     I agree that header-library version mismatches would constitute a broken build, but, the broken build may still run.
     This could be the kind of thing you want to show in an "About" popup or to an administrator at startup or in log.
     Completely fine it's not so high granularity on the version numbers.)

**Comment by mlmikael** [comment]
(I agree such a value by no standard is a guarantee for proper functioning, but, at least you'll know you're in the right ballpark - if ever there'd be an urgent patch like security or important network update, I guess the version number would bump, for instance.)

**Comment by evoskuil** [comment]
The chance of this making a difference between actual *releases* is slim. Changes in the major release number correspond breaking changes. Changes in the minor number are forward compatible changes, which are moot - except maybe to a developer, but in the case where a developer is working between reversioned builds, this scheme won't work (I suspect this is where you hit the issue). And changes to the "patch" build number (rarely used) are immaterial source changes.

Of course there could be impactful changes that don't affect a function signature (i.e. internal to a function) and if someone wanted to track this down they would need to potentially chase down all dependencies. I could justify adding the release version info to a library function in each repo for this reason. Note that the sceanrio isn't limited to shared libs.

I wouldn't rely on anything that openssl does as [evidence of a best practice](https://www.peereboom.us/assl/assl/html/openssl.html) :).

**Comment by evoskuil** [comment]
I looked at this again and can't come up with a reason to expose a function that returns the public constant. The function would be declared inline in the same header as the constant, making the distinction purely cosmetic.
