### ISSUE TITLE
Stealth address version altchain support.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin#318]
[Stealth addresses](https://wiki.unsystem.net/en/index.php/DarkWallet/Stealth) suffer from a presumed mapping to bitcoin p2pkh versions 42/43 <-> 0/111. 
```
Address format
BTC version = 0x2a (42) testnet BTC version = 0x2b (43)
```
We would prefer that this map to bitcoin payment addresses deterministically. Ideally the version byte would simply be the payment address version byte. 

Address length is sufficient disambiguation. There's no point in a distinct set of versions if there is to be a 1:1 mapping - as there will be 100% overlap and it will just be unnecessarily confusing. The only reason we couldn't do this simpler mapping in `BIP-38` was that it was already in widespread use. But stealth design is still somewhat fluid. 

Given that stealth addresses are long, there is also a desire to keep the length down, adding more bytes for cosmetics has a material downside.

**Comment by skaht** [comment]
Just a thought... The size of stealth addresses are VERY close to the extended BIP38 encoded keys for altcoins. Might be worthwhile to have a distinguishing feature.

**Comment by skaht** [comment]
Need to see the updated [table](https://github.com/libbitcoin/libbitcoin/wiki/BIP44-Altcoin-Version-Mappings#bip44-altcoin-version-mapping-table).  Added a version/p2sh column and recommendation for script-to-address for multisig addresses. Not sure yet if this will have an impact on stealth multisig signatures yet.

**Comment by skaht** [comment]
Glance at this [update](https://github.com/libbitcoin/libbitcoin/wiki/BIP44-Altcoin-Version-Mappings#bx---encoding-commands).  Thinking more table columns may be needed to adequately support stealth addresses, and stealth multisig addresses.

Important source code variable mapping to table columns that I ran across are:
1. version/WIF -> [SECRET_KEY](https://github.com/bitcoin/bitcoin/blob/master/src/chainparams.cpp#L106)
2. version/p2pkh -> [PUBKEY_ADDRESS](https://github.com/bitcoin/bitcoin/blob/master/src/chainparams.cpp#L104) or ADDRESS_VERSION
3. version/p2sh -> [SCRIPT_ADDRESS](https://github.com/bitcoin/bitcoin/blob/master/src/chainparams.cpp#L105)

Suspect similar ones might arise for stealth (notional):
4. version/sp2pkh ->  STEALTH_PUBKEY_ADDRESS or STEALTH_ADDRESS_VERSION
5. version/sp2sh -> STEALTH_SCRIPT_ADDRESS

I'm really liking the idea of eventually updating the [table](https://github.com/libbitcoin/libbitcoin/wiki/BIP44-Altcoin-Version-Mappings#bip44-altcoin-version-mapping-table) with kind of row/column traceability in 1, 2 abd 3 above.

**Comment by evoskuil** [comment]
I think that in order to minimize expanding complexity, I would like to see `stealth_address` use the same version byte as `payment_address`. There is no reason that I can see to differentiate them.

One oddity is that with multisig stealth payments (which are not fully implemented) the redeem script would presumably be P2SH, though this differentiation isn't really required in stealth addresses. So a mapped P2SH version would be redundant with a mapped P2PKH version.

This is sufficient programmatic chain differentiation. Creating additional cosmetic differentiation may be desirable, but that's a bit beyond current scope.

**Comment by skaht** [comment]
Something to be said about keeping it simple and trying to reuse:

1) wif_version (version/WIF), 
2) pubkey_version (version/p2pkh), 
3) script_version (version/p2sh) whenever possible.

**Comment by evoskuil** [comment]
current code defaults to use of payment address versioning for stealth addresses.
