### ISSUE TITLE
Make "standard" size of OP_RETURN configurable.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin#363]
The current size for "standard" treatment of `OP_RETURN` is fixed at 80 bytes, although there are no policy restrictions. This also affects indexing of stealth outputs.

**Comment by skaht** [comment]
Interesting concept...

**Comment by evoskuil** [comment]
After further review I've decided to leave this fixed so that we don't end up with what are effectively parameterized tx pool soft forks in script eval. However by disabling this policy one will be able to allow any size and control by simply charging for the space via fees per byte. Additionally I'm not planning to implement the "standard" policy of one OP_RETURN per tx for similar reasons. This just encourages more waste by pushing the same data into more block bytes. It's better to just raise the fee and get fewer bytes for the same price.
