### ISSUE TITLE
bogus copyright range: 2011-2018

### ISSUE THREAD

**Issue by jonassmedegaard** [libbitcoin/libbitcoin#389]
I am not a lawyer, but I believe copyright coverage only ever makes sense to state for years of actual authoring/releasing code.

We have 2016 now, yet 4 files claim a copyright coverage rainging into 2018:

include/bitcoin/bitcoin/network/channel.hpp
include/bitcoin/bitcoin/network/protocol.hpp
src/network/channel.cpp
src/network/protocol.cpp

**Comment by evoskuil** [comment]
Fixed. Do you need the tag moved up?

**Comment by jonassmedegaard** [comment]
Quoting Eric Voskuil (2016-04-25 10:16:30)
> Fixed. Do you need the tag moved up?

If you mean if I need a new release of the corrected source for Debian 
redistribution, then no: I have worked around it by use of temporary 
comments in debian/copyright file.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
