### ISSUE TITLE
Outdated reference to LICENSE file and libssl exception.

### ISSUE THREAD

**Issue by jonassmedegaard** [libbitcoin/libbitcoin#390]
The LICENSE file was renamed 2 years ago (commit fdb87bb) and libssl exception dropped a year ago (commit 2f7bdde), yet pretty consistently both are still referenced in licensing headers.

**Comment by evoskuil** [comment]
I don't see SSL referenced anywhere in this repo except for big_number.hpp/cpp test code, which has the openssl references disabled. Is this what you are referring to?

I see the reference to the file LICENSE in the copyrights. I'll change those to COPYING. The name was changed some time ago to comport to the GNU expectations of:

- INSTALL
- NEWS
- README
- COPYING
- AUTHORS
- ChangeLog

**Comment by evoskuil** [comment]
LICENSE has been replaced with COPYING in the copyright headers.

**Comment by jonassmedegaard** [comment]
Quoting Eric Voskuil (2016-04-25 10:34:39)
> I don't see SSL referenced anywhere in this repo except for 
> big_number.hpp/cpp test code, which has the openssl references 
> disabled. Is this what you are referring to?

What I am referring to is the difference between generic boilerplate 
license grant as recommended at the top of your COPYING file:

> This program is free software: you can redistribute it and/or modify 
> it under the terms of the GNU Affero General Public License as 
> published by the Free Software Foundation, either version 3 of the 
> License, or (at your option) any later version.

...and the actual license grant used throughout the code:

> libbitcoin is free software: you can redistribute it and/or modify it 
> under the terms of the GNU Affero General Public License with 
> additional permissions to the one published by the Free Software 
> Foundation, either version 3 of the License, or (at your option) any 
> later version. For more information see LICENSE.

In particular the "with additional permissions" part.


I recommend to use the generic boilerplate verbatim (not even mention 
"libbitcoin" in that paragraph, just the generic "This program").


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by evoskuil** [comment]
And regarding SSL?

**Comment by evoskuil** [comment]
So change this:

```cpp
/**
 * Copyright (c) 2011-2015 libbitcoin developers (see AUTHORS)
 *
 * This file is part of libbitcoin.
 *
 * libbitcoin is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License with
 * additional permissions to the one published by the Free Software
 * Foundation, either version 3 of the License, or (at your option)
 * any later version. For more information see LICENSE.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
```
...to this:
```cpp

/**
 * Copyright (c) 2011-2015 libbitcoin developers (see AUTHORS)
 *
 * This file is part of libbitcoin.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
```

**Comment by jonassmedegaard** [comment]
Quoting Eric Voskuil (2016-04-25 22:18:44)
> So change this:
> 
> ```cpp
> /**
>  * Copyright (c) 2011-2015 libbitcoin developers (see AUTHORS)
>  *
>  * This file is part of libbitcoin.
>  *
>  * libbitcoin is free software: you can redistribute it and/or modify
>  * it under the terms of the GNU Affero General Public License with
>  * additional permissions to the one published by the Free Software
>  * Foundation, either version 3 of the License, or (at your option)
>  * any later version. For more information see LICENSE.
>  *
>  * This program is distributed in the hope that it will be useful,
>  * but WITHOUT ANY WARRANTY; without even the implied warranty of
>  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>  * GNU Affero General Public License for more details.
>  *
>  * You should have received a copy of the GNU Affero General Public License
>  * along with this program. If not, see <http://www.gnu.org/licenses/>.
>  */
> ```
> ...to this:
> ```cpp
> 
> /**
>  * Copyright (c) 2011-2015 libbitcoin developers (see AUTHORS)
>  *
>  * This file is part of libbitcoin.
>  *
>  * This program is free software: you can redistribute it and/or modify
>  * it under the terms of the GNU Affero General Public License as published by
>  * the Free Software Foundation, either version 3 of the License, or
>  * (at your option) any later version.
>  * 
>  * This program is distributed in the hope that it will be useful,
>  * but WITHOUT ANY WARRANTY; without even the implied warranty of
>  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>  * GNU Affero General Public License for more details.
>  *
>  * You should have received a copy of the GNU Affero General Public License
>  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
>  */
> ```

Yes.

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by evoskuil** [comment]
OK, I'll update them all in version2 and master. Might be a couple days before I get to it.

**Comment by evoskuil** [comment]
@jonassmedegaard Never got to this in version2, but we are going to get this done before the version3 release is tagged, which will be this week.

**Comment by evoskuil** [comment]
Complete, thanks @pmienk
