### ISSUE TITLE
Old style sig scripts cause missing history reporting in server.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin#393]
https://github.com/libbitcoin/libbitcoin-explorer/issues/342

**Comment by RojavaCrypto** [comment]
From libbitcoin/libbitcoin-explorer#342

`bc::payment_address` lacks support for reading old style `[ pubkey ] OP_CHECKSIG` and `[ M ] ... OP_CHECKMULTISIG` style addresses.

**Comment by evoskuil** [comment]
This should be resolved due to evolution of both script_pattern parsing and payment_address.

**Comment by evoskuil** [comment]
Payment addresses now parse these scripts, as well as bare multisig. But these are contained output scripts which are not always accessible to the server during input processing (specifically when under checkpoints). As such the server currently does not index these (nonstandard) payment types.
