### ISSUE TITLE
Doc: Installation - Debian/Ubuntu

### ISSUE THREAD

**Issue by nicknameul** [libbitcoin/libbitcoin#396]
Hello.

I tried to install this library and i could not do it because of a mistake in the script installation link.
In Doc you have the following link : 

wget https://raw.githubusercontent.com/libbitcoin/libbitcoin/version2/install.sh 

when the one that worked for me was : 

wget https://raw.githubusercontent.com/libbitcoin/libbitcoin/master/install.sh

If noob issue, i do apologize, but i just wanted to help.
GG on the code

**Comment by evoskuil** [comment]
Hi @nicknameul - what error do you get with the  version2 install?

**Comment by skaht** [comment]
Try downloading bitcoin-explorer and bitcoin-server using the following git commands:

1. git clone --branch version2 --single-branch https://github.com/libbitcoin/libbitcoin-explorer
2. git clone --branch version2 --single-branch https://github.com/libbitcoin/libbitcoin-server

Then try running the install.sh scripts for bitcoin-explorer and bitcoin-server.

**Comment by nicknameul** [comment]
I'm not able to replicate the error now. Tried to reinstall version 2 now, but it all worked as planned. I thought that it did not work to install that version because Master was the new one and somebody forgot to update the Doc. I'm a total newb when it comes to this.

**Comment by evoskuil** [comment]
@skant - it's not necessary to clone, as the install script does this.

**Comment by nicknameul** [comment]
@skaht - Installed with git clone command. Now i can call bx anytime in Ubuntu terminal. Thanks

**Comment by skaht** [comment]
@nicknameul - Eric is right that the approach I recommended was not a minimalist approach. The initial clone was an overkill because it downloads a complete distribution for a given branch.

**Comment by skaht** [comment]
Think Eric meant something like the following should have been done:

A1. ```wget -O bx-install.sh https://raw.githubusercontent.com/libbitcoin/libbitcoin-explorer/version2/install.sh```
A2. ```chmod u+x bx-install.sh```
A3. ```./bx-install.sh --build-icu --build-boost --build-dir=`pwd`/build-bs --prefix=`pwd`/install-bx --disable-shared```

B1. ```wget -O bs-install.sh https://raw.githubusercontent.com/libbitcoin/libbitcoin-server/version2/install.sh```
B2. ```chmod u+x bs-install.sh```
B3. ```./bs-install.sh --build-boost --build-dir=`pwd`/build-bs --prefix=`pwd`/install-bs --disable-shared```
