### ISSUE TITLE
Building on a new system with libbitcoin secp256k1 causes fatal build error

### ISSUE THREAD

**Issue by RojavaCrypto** [libbitcoin/libbitcoin#397]
`src/math/elliptic_curve.cpp:24:32: fatal error: secp256k1_recovery.h: No such file or directory`

Can provide more info if needed.

**Comment by evoskuil** [comment]
Hey, sorry about that. The installer builds with `--enable-module-recovery`, which can be seen [here](https://github.com/libbitcoin/libbitcoin/blob/master/install.sh#L238). This option is off by default, but we use the recovery module for minisig, so it's required to build libbitcoin. I'll update the libbitcoin readme.md.

We maintain the libbitcoin/libsecp256k1 fork for two reasons. (1) The library is unversioned and there have been frequent interface changes. By freezing the source of a build until a future time when more recent changes can be verified, we stabilize the dependency. (2) To retain the additional sources for the MSVC builds. We don't make any changes to the library, so as long as the interface hasn't changed you can build from to current head of bitcoin-core.

**Comment by djsamperi** [comment]
Instructions for building libbitcoin/libbitcoin suggest that we should use libbitcoin/secp256k1, but secp256k1_recovery.h does not exist in the latter. It does exist in bitcoin-core/secp256k1, but libbitcoin does not build with this version. There is no --enable-module-recovery option in the configure menu for libbitcoin. What am I missing?
