### ISSUE TITLE
Missing/not installed include file secp256k1_recovery.h, cannot build

### ISSUE THREAD

**Issue by TiVoMaker** [libbitcoin/libbitcoin#404]
Cloned and installed libbitcoin/secp256k1. Cloned libbitcoin/libbitcoin. After adding PKG_CONFIG_PATH to point at /usr/local/lib/pkgconfig, configured successfully.

Compile fails:

src/math/elliptic_curve.cpp:24:32: fatal error: secp256k1_recovery.h: No such file or directory
 #include <secp256k1_recovery.h>

And indeed, no such header was installed, nor does it exist in libbitcoin/secp256k1.

Checking bitcoin-core/secp256k1 (upstream), the include directory does indeed contain a  secp256k1_recovery.h header, but neglects to install it as well.

**Comment by evoskuil** [comment]
See: https://github.com/libbitcoin/libbitcoin/blob/master/README.md#installation

**Comment by TiVoMaker** [comment]
Fair enough, that allows building with the original secp256k1 from bitcoin-core.

However, it doesn't address why I can't build with the secp256k1 from the libbitcoin project. Are they expected to be out of sync?

**Comment by RojavaCrypto** [comment]
Yes for the current master we are staying with the mainline version. The one that exists in our repo is for our last release (version 2) so people can still compile it (the version was frozen). But for the master, you should use their repo version. I'm closing the bug unless you think it should be open (just write). If you use the install.sh script install method, you should get a full built server and all the libs install with minimal hassle.

**Comment by evoskuil** [comment]
The origin repo version will be fine as long as it doesn't change its interface again. For this reason our installer uses our fork.
