### ISSUE TITLE
Errors during compilation of libbitcoin

### ISSUE THREAD

**Issue by findftp** [libbitcoin/libbitcoin#408]
I'm a noob, and learning.
First the installer complained about libboost being to old (1.55) so I compiled the newest libboost version 1.61, presumably without errors.
When I tried to install libbitcoin again, I got new errors.
Now I'm on a dead end, I don't know what to do.
This is the last part of the installer just before it quits:

```
CXXLD examples/libbitcoin_examples
src/.libs/libbitcoin.so: undefined reference to boost::re_detail_106100::put_mem_block(void*)' src/.libs/libbitcoin.so: undefined reference toboost::re_detail_106100::get_default_error_string(boost::regex_constants::error_type)'
src/.libs/libbitcoin.so: undefined reference to boost::re_detail_106100::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const' src/.libs/libbitcoin.so: undefined reference toboost::re_detail_106100::get_mem_block()'
src/.libs/libbitcoin.so: undefined reference to boost::re_detail_106100::verify_options(unsigned int, boost::regex_constants::_match_flags)' src/.libs/libbitcoin.so: undefined reference toboost::re_detail_106100::raise_runtime_error(std::runtime_error const&)'
src/.libs/libbitcoin.so: undefined reference to boost::re_detail_106100::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const' src/.libs/libbitcoin.so: undefined reference toboost::re_detail_106100::perl_matcher<__gnu_cxx::__normal_iterator, std::allocator > >, boost::regex_traits > >::construct_init(boost::basic_regex > > const&, boost::regex_constants::_match_flags)'
collect2: error: ld returned 1 exit status
make: *** [examples/libbitcoin_examples] Error 1

```

I'm on Linux mint 17.3, please help.

**Comment by evoskuil** [comment]
Did your build include the boost::regex?

I generally reccomend using install.sh with the --build-boost and --prefix options.

**Comment by findftp** [comment]
Have been busy with it for 4 hours without success.
My last attempt was:
sudo ./install.sh --with-bash-completion-dir --disable-shared --build-boost --prefix=/home/michiel/Downloads/boost_1_56_0

This is the result:
============================================================================
Testsuite summary for libbitcoin-explorer 2.2.0
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================

michiel@zolder ~/Downloads $ bx
bx: command not found


Any other options than just use the pre built binary?

**Comment by findftp** [comment]
Ok, I'm a noob, I know. Hopefully this will change sometime in the future...
That prefix should have pointed to the /bin directory I suppose.
I searched system wide for 'bx' and found the program in the boost directory :-/
Seems to be working now...
Thanks

**Comment by RojavaCrypto** [comment]
--prefix should be the root of where the install goes. By default it is /usr/local/

If you want to install it locally, then do this:

$ mkdir usr
$ ... --prefix /home/michiel/usr/

Then edit ~/.bashrc and add these variables:

export PKG_CONFIG_PATH=/home/michiel/usr/lib/pkgconfig/
export PATH=$PATH:/home/michiel/usr/bin/
export LD_LIBRARY_PATH=/home/michiel/usr/lib/

good luck

**Comment by evoskuil** [comment]
The bashrc edit for LD_LIBRARY_PATH should no longer be required. The dynamic libraries now incorporate their own references (and static are self-contained). PKG_CONFIG_PATH can be avoided if not developing against the libs.

**Comment by findftp** [comment]
I already got it going, but thanks anyway for the support!
