### ISSUE TITLE
Logging subsystem consumes file lock which stops OS from seeing freed disk space

### ISSUE THREAD

**Issue by RojavaCrypto** [libbitcoin/libbitcoin#447]
There needs to be a piece of code in the logging subsystem which closes, and re-opens the file handle every 30 mins or so.

I have logrotation working on my Linux box but because the server does not release the file locks, the filesystem doesn't see the free space.

For example:

```/dev/vda1        89G   85G     0 100% /```

Reports 100% disk usage.

However the log file is 300Kb:

```
$ cat /usr/local/etc/libbitcoin/bs.cfg | grep debug
# The debug log file path, defaults to 'debug.log'.
debug_file = /var/log/libbitcoin/debug.log

$ ls -hl /var/log/libbitcoin/ 
total 636K
-rw-r--r-- 1 lb lb 439K Aug 20 15:11 debug.log
-rw-rw-r-- 1 lb lb 189K Aug 20 15:08 error.log
```

If I restart the server then suddenly the disk space will re-appear again:

```/dev/vda1        89G   69G   16G  82% /```

**Comment by RojavaCrypto** [comment]
Are there plans for version3 to move to the boost logging system or should I proceed with submitting a patch for this issue? Thanks.

**Comment by evoskuil** [comment]
I'm guessing [this peposed change](https://github.com/libbitcoin/libbitcoin/issues/307) will resolve this issue.

**Comment by RojavaCrypto** [comment]
Yep, it will most likely (looking over their API). Feel free to close this bug report.
