### ISSUE TITLE
Missing implementations for chain::(transaction, input, output)::satoshi_fixed_size

### ISSUE THREAD

**Issue by RojavaCrypto** [libbitcoin/libbitcoin#454]
```
undefined reference to `libbitcoin::chain::input::satoshi_fixed_size()'
undefined reference to `libbitcoin::chain::transaction::satoshi_fixed_size()'
undefined reference to `libbitcoin::chain::output::satoshi_fixed_size()'
```

Can I delete these functions? I'm not sure what their purpose is. None of these objects has a fixed size.

**Comment by pmienk** [comment]
Sure, they shouldn't be there.

**Comment by RojavaCrypto** [comment]
Please merge this pull request and close this ticket if you think this change is fine:

https://github.com/libbitcoin/libbitcoin/pull/455
