### ISSUE TITLE
secp256k1_recovery.h: No such file or directory

### ISSUE THREAD

**Issue by betachen** [libbitcoin/libbitcoin#456]
Here is when I compile libbitcoin what happened:

> src/math/elliptic_curve.cpp:24:32: fatal error: secp256k1_recovery.h: No such file or directory
> compilation terminated.
> Makefile:2976: recipe for target 'src/math/src_libbitcoin_la-elliptic_curve.lo' failed
> make: *** [src/math/src_libbitcoin_la-elliptic_curve.lo] Error 1

I found that libbitcoin/secp256k1 which has missed "secp256k1_recovery.h" is 224 commits behind bitcoin-core:master.

Hence, I pulled bitcoin/secp256k1 => make & make install.
It still lost  "secp256k1_recovery.h" in procedure installing to $prefix_path.
I'm not sure if it's a project bug?

obviously, I copyed "secp256k1_recovery.h" to $prefix_path, it worked. howerver, I got another issue when gcc linking:
>   CXXLD    examples/libbitcoin_examples
> src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recover'
> src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_sign_recoverable'
> src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recoverable_signature_serialize_compact'
> src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recoverable_signature_parse_compact'

Is that miss  "secp256k1_recovery.h"  for libbitcoin in gnu automake configures?

ENV:
OS=> Ubuntu 16.04 LTS (GNU/Linux 4.4.0-21-generic x86_64)
Compiler=> gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.1)

Finally, I create a cmake project for libbitcoin, it seems worked well.
but ,I got too many compiling warnings if not use those flags as below:
> -Wno-reorder -Wno-ignored-qualifiers -Wno-unused-function.

like as: _const func() const_ for Wno-reorder
like as: _const int ret& func(){ return int}_  for -Wno-ignored-qualifiers.

Will that be repaired?

Thanks.

**Comment by RojavaCrypto** [comment]
Hi, when you configure secp256k1, you need the switch --enable-recovery (see the --help).

Normally we encourage people to use the install script so dependencies are made without confusion, but building manually is also fine. See the README for more info: https://github.com/libbitcoin/libbitcoin/blob/version2/README.md

When you build a project (assuming you're on Linux), you can use `pkg-config --cflags --libs libbitcoin`. Also you must add `-std=c++11`

**Comment by RojavaCrypto** [comment]
BTW the install script can also install to a given prefix.

**Comment by betachen** [comment]
To be honest, I really thought install script is not good for developer.

**Actually, I meaning that is there some compile warning in libbitcoin if without "-Wno-reorder -Wno-ignored-qualifiers", not -std=c++11.** 
even it's not critical for code, _const func() const,_  allright, not bad. ☺

Thanks for the "--enable-recovery" options.

**Comment by evoskuil** [comment]
> configure: WARNING: unrecognized options: --enable-recovery

Are you using the libbitcoin libsecp256k1 repo?

**Comment by betachen** [comment]
thanks for reply.

It's resolved on libsecp256k1 issue , because of i used bitcoin/secp256k1 , not same options for "--enable-recovery", it's "--enable-module-recovery".
---------------------
** I  am converting libbitcoin gnu automake to cmake tools, so i found there was so many warnings occurred and problems**

I found that I have to add "-Wno-reorder -Wno-ignored-qualifiers" in CXX_FLAGS, so i m not sure what happen there.

thanks again.

**Comment by evoskuil** [comment]
Hi @betachen, the seeds queried are those configured in the .cfg file (or by default as documented in the .cfg sameple). If you still have issues please open and issue under `libbitcoin-network`.
