### ISSUE TITLE
Minor build error

### ISSUE THREAD

**Issue by thecodefactory** [libbitcoin/libbitcoin#533]
Currently including bitcoin.hpp from another project results in this error:

```
include/bitcoin/bitcoin/constants.hpp: In function ‘constexpr uint64_t libbitcoin::max_money()’:
include/bitcoin/bitcoin/constants.hpp:157:1: error: body of constexpr function ‘constexpr uint64_t libbitcoin::max_money()’ not a return-statement
```

Looks like the assert not being compiled out causes this:

```
BC_CONSTFUNC uint64_t max_money()
{
    /* // Optimize out the derivation of recursive_money, verify in debug builds. */
    BITCOIN_ASSERT(recursive_money == max_money_recursive(
        initial_block_reward_satoshi()));

    return reward_interval * recursive_money;
}
```

Would issue a PR, but not sure how you'd prefer to resolve it (e.g. keep the assert and drop constexpr, or drop the assert, or whatever else).

**Comment by evoskuil** [comment]
VC+ doesn't have constfunc so I used the assertion, but that needs to be a static assert inside of the non-VC++ constfunc. But can't use static assert with the recursive non-const recursive func :/. I'll just disable the assertion.

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin/pull/534

**Comment by thecodefactory** [comment]
👍
