### ISSUE TITLE
secp256k1_recovery.h missing

### ISSUE THREAD

**Issue by djsamperi** [libbitcoin/libbitcoin#570]

**Comment by thecodefactory** [comment]
Unless you are advanced and used to building libbitcoin, I highly recommend using the install.sh scripts in each of the repos to complete the build.  They take care of gathering all required dependencies.

Let me know if that helps.

**Comment by thecodefactory** [comment]
The actual answer is that the required version of secp256k1 includes the missing file you're referencing.

**Comment by evoskuil** [comment]
> A minimal libbitcoin build requires boost and libsecp256k1. The libbitcoin/secp256k1 repository is forked from bitcoin-core/secp256k1 in order to control for changes and to incorporate the necessary Visual Studio build. The original repository can be used directly but recent changes to the public interface may cause build breaks. The --enable-module-recovery switch is required.

https://github.com/libbitcoin/libbitcoin#installation
