### ISSUE TITLE
How can I look at every block?

### ISSUE THREAD

**Issue by whackashoe** [libbitcoin/libbitcoin#604]
I want to look at the transactions in every block for analysis but I'm having a hard time finding out how to. The Satoshi's words example really only helps for looking at the first one. From what I can tell that block is just embedded in the code anyways and not being loaded from a data file. Anyways, if someone could point me in right direction would be appreciated, thanks.

**Comment by evoskuil** [comment]
You can't do this with the base libbitcoin library as it does not have every block. You'll either need to run a client, like `libbitcoin-client` or `libbitcoin-explorer`, or a client command line tool like `bx`, or a node like `libbitcoin-node` or `libbitcoin-server` and write code directly against it.

**Comment by whackashoe** [comment]
Ah, thanks for the advice. No wonder I wasn't having any luck. Cheers.
