### ISSUE TITLE
<bitcoin/bitcoin/utility/variable_uint_size.hpp> or <bitcoin/bitcoin/message/messages.hpp>?

### ISSUE THREAD

**Issue by RojavaCrypto** [libbitcoin/libbitcoin#628]
There is no implementation for <bitcoin/bitcoin/utility/variable_uint_size.hpp>, however the function appears in <bitcoin/bitcoin/message/messages.hpp>.

So either an implementation needs to be added in src/utility/variable_uint_size.cpp or the header should be removed. If the impl is added, then references inside message need to be updated. I can do this task, I just don't know which approach is preferred.

**Comment by evoskuil** [comment]
I believe that is a dead file, the implementation is elsewhere but it is there. I'll check in a bit.

**Comment by RojavaCrypto** [comment]
OK understood. See this pull req: https://github.com/libbitcoin/libbitcoin/pull/629

**Comment by evoskuil** [comment]
Thanks!

**Comment by evoskuil** [comment]
I've added a PR to remove the file as well. Otherwise our source generation will simply roll back your change.
