### ISSUE TITLE
Can show project Metaverse  in libbitcoin.org web page?

### ISSUE THREAD

**Issue by betachen** [libbitcoin/libbitcoin#764]
[metaverse](https://github.com/mvs-live/metaverse) project was implemented based on libbitcoin libraires, I want to put metaverse logo on libbitcoin.org, just like openbazaar. And we want libbitcoin logo on metaverse index page as well, could you send me original libbitcoin logo file?
Metaverse is a blockchain project that can build more new applications beyond bitcoin. see details [here](http://mvs.live)

**Comment by evoskuil** [comment]
@betachen This is great, thanks for the info and congratulations!

I've added metaverse [here](https://en.bitcoin.it/wiki/Libbitcoin#Projects_Using_Libbitcoin).

The original logo is [here](https://en.bitcoin.it/wiki/File:Libbitcoin-logo.png).

I don't have access to [libbitcoin.org](https://libbitcoin.org). Please post to the mailing list and someone should take care of it.

**Comment by betachen** [comment]
Thanks for your help, Eric.
