### ISSUE TITLE
Build error in Mac OS Sierra

### ISSUE THREAD

**Issue by aparesse** [libbitcoin/libbitcoin#777]
/usr/local/include/boost/multiprecision/detail/functions/constants.hpp:246:47: error: initializer for thread-local variable must be a constant expression
   static BOOST_MP_THREAD_LOCAL long digits = boost::multiprecision::detail::digits2<number<T> >::value();
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/multiprecision/detail/functions/constants.hpp:246:38: note: use 'thread_local' to allow this
   static BOOST_MP_THREAD_LOCAL long digits = boost::multiprecision::detail::digits2<number<T> >::value();
                                     ^
/usr/local/include/boost/multiprecision/detail/functions/constants.hpp:267:47: error: initializer for thread-local variable must be a constant expression
   static BOOST_MP_THREAD_LOCAL long digits = boost::multiprecision::detail::digits2<number<T> >::value();
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/multiprecision/detail/functions/constants.hpp:267:38: note: use 'thread_local' to allow this
   static BOOST_MP_THREAD_LOCAL long digits = boost::multiprecision::detail::digits2<number<T> >::value();
                                     ^
/usr/local/include/boost/multiprecision/detail/functions/constants.hpp:285:47: error: initializer for thread-local variable must be a constant expression
   static BOOST_MP_THREAD_LOCAL long digits = boost::multiprecision::detail::digits2<number<T> >::value();
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/multiprecision/detail/functions/constants.hpp:285:38: note: use 'thread_local' to allow this
   static BOOST_MP_THREAD_LOCAL long digits = boost::multiprecision::detail::digits2<number<T> >::value();
                                     ^
In file included from src/utility/random.cpp:28:
In file included from ./include/bitcoin/bitcoin/constants.hpp:25:
In file included from ./include/bitcoin/bitcoin/config/checkpoint.hpp:27:
In file included from ./include/bitcoin/bitcoin/formats/base_16.hpp:24:
In file included from ./include/bitcoin/bitcoin/math/hash.hpp:26:
In file included from /usr/local/include/boost/multiprecision/cpp_int.hpp:12:
In file included from /usr/local/include/boost/multiprecision/number.hpp:22:
In file included from /usr/local/include/boost/multiprecision/detail/generic_interconvert.hpp:9:
In file included from /usr/local/include/boost/multiprecision/detail/default_ops.hpp:1667:
/usr/local/include/boost/multiprecision/detail/functions/pow.hpp:418:47: error: initializer for thread-local variable must be a constant expression
   static BOOST_MP_THREAD_LOCAL long digits = boost::multiprecision::detail::digits2<number<T> >::value();
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/multiprecision/detail/functions/pow.hpp:418:38: note: use 'thread_local' to allow this
   static BOOST_MP_THREAD_LOCAL long digits = boost::multiprecision::detail::digits2<number<T> >::value();
                                     ^
4 errors generated.

install script:
wget https://raw.githubusercontent.com/libbitcoin/libbitcoin/version3/install.sh

 g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.38)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

boost version 1.6.4

**Comment by evoskuil** [comment]
See: https://github.com/libbitcoin/libbitcoin/issues/733

**Comment by evoskuil** [comment]
Thanks for reporting, but closing as duplicate issue.

**Comment by aparesse** [comment]
thanks
