### ISSUE TITLE
Boost related error occurs when building libbitcoin on Ubuntu 16 LTS 

### ISSUE THREAD

**Issue by ziyoustep** [libbitcoin/libbitcoin#791]
I have install ed boost library using  sudo apt-get install libboost-all-dev  but these errors still occur 

copying selected object files to avoid basename conflicts...
```
ar: `u' modifier ignored since `D' is the default (see `U')
  CXX      examples/examples_libbitcoin_examples-main.o
  CXXLD    examples/libbitcoin_examples
src/.libs/libbitcoin.so: undefined reference to `boost::log::v2_mt_posix::sinks::text_file_backend::consume(boost::log::v2_mt_posix::record_view const&, std::string const&)'
src/.libs/libbitcoin.so: undefined reference to `boost::re_detail_106400::put_mem_block(void*)'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::to_internal(std::string const&)'
src/.libs/libbitcoin.so: undefined reference to `boost::re_detail_106400::verify_options(unsigned int, boost::regex_constants::_match_flags)'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::option_description::long_name() const'
src/.libs/libbitcoin.so: undefined reference to `boost::re_detail_106400::get_default_error_string(boost::regex_constants::error_type)'
src/.libs/libbitcoin.so: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::option_description::format_name() const'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::option_description::format_parameter() const'
src/.libs/libbitcoin.so: undefined reference to `boost::log::v2_mt_posix::sinks::basic_text_ostream_backend<char>::consume(boost::log::v2_mt_posix::record_view const&, std::string const&)'
src/.libs/libbitcoin.so: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
src/.libs/libbitcoin.so: undefined reference to `void boost::log::v2_mt_posix::aux::put_integer<char>(boost::log::v2_mt_posix::aux::basic_ostringstreambuf<char, std::char_traits<char>, std::allocator<char> >&, unsigned int, unsigned int, char)'
src/.libs/libbitcoin.so: undefined reference to `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
src/.libs/libbitcoin.so: undefined reference to `boost::re_detail_106400::raise_runtime_error(std::runtime_error const&)'
src/.libs/libbitcoin.so: undefined reference to `boost::re_detail_106400::cpp_regex_traits_implementation<char>::transform_primary(char const*, char const*) const'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::positional_options_description::name_for_position(unsigned int) const'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::option_description::description() const'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
src/.libs/libbitcoin.so: undefined reference to `boost::re_detail_106400::cpp_regex_traits_implementation<char>::transform(char const*, char const*) const'
src/.libs/libbitcoin.so: undefined reference to `boost::re_detail_106400::get_mem_block()'
src/.libs/libbitcoin.so: undefined reference to `boost::log::v2_mt_posix::aux::code_convert_impl(wchar_t const*, unsigned long, std::string&, unsigned long, std::locale const&)'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::parse_environment(boost::program_options::options_description const&, std::string const&)'
collect2: error: ld returned 1 exit status
Makefile:2179: recipe for target 'examples/libbitcoin_examples' failed
make: *** [examples/libbitcoin_examples] Error 1
```

**Comment by evoskuil** [comment]
Hi @ziyoustep, clearly there is a problem with the boost dependency.  It is linking to a library that is missing the listed references. Check your version of boost and the install libraries for starters. You could also post the full build log, which will provide more detail.

**Comment by ziyoustep** [comment]
## **These are the ./configure log  information. It shows that I have installed those dependencies. But it still not work for me.**
-----------------------------------------------
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for style of include used by make... GNU
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking dependency style of g++... (cached) gcc3
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=c++11... yes
checking --with-pkgconfigdir option... ${exec_prefix}/lib/pkgconfig
checking --with-tests option... yes
checking --with-examples option... yes
checking --with-icu option... no
checking --with-png option... no
checking --with-qrencode option... no
checking --enable-ndebug option... yes
checking for boostlib >= 1.57.0... yes
configure: boost_CPPFLAGS : -I/usr/include
configure: boost_LDFLAGS : -L/usr/lib/x86_64-linux-gnu
checking whether the Boost::Chrono library is available... yes
checking for exit in -lboost_chrono... yes
configure: boost_chrono_LIBS : -lboost_chrono
checking whether the Boost::Date_Time library is available... yes
checking for exit in -lboost_date_time... yes
configure: boost_date_time_LIBS : -lboost_date_time
checking whether the Boost::Filesystem library is available... yes
checking for exit in -lboost_filesystem... yes
configure: boost_filesystem_LIBS : -lboost_filesystem
checking whether the Boost::IOStreams library is available... yes
checking for exit in -lboost_iostreams... yes
configure: boost_iostreams_LIBS : -lboost_iostreams
checking whether the Boost::Locale library is available... yes
checking for exit in -lboost_locale... yes
configure: boost_locale_LIBS : -lboost_locale
checking whether the Boost::Log library is available... yes
checking for exit in -lboost_log... yes
configure: boost_log_LIBS : -lboost_log
checking whether the Boost::Program_Options library is available... yes
checking for exit in -lboost_program_options... yes
configure: boost_program_options_LIBS : -lboost_program_options
checking whether the Boost::Regex library is available... yes
checking for exit in -lboost_regex... yes
configure: boost_regex_LIBS : -lboost_regex
checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... yes
configure: boost_system_LIBS : -lboost_system
checking whether the Boost::Thread library is available... yes
checking for exit in -lboost_thread... yes
configure: boost_thread_LIBS : -lboost_thread
checking whether the Boost::Unit_Test_Framework library is available... yes
configure: boost_unit_test_framework_LIBS : -lboost_unit_test_framework
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
configure: pthread_CPPFLAGS : 
configure: pthread_LIBS : 
checking for clock_gettime in -lrt... yes
configure: rt_LIBS : -lrt
checking for dlopen in -ldl... yes
configure: dl_LIBS : -ldl
checking for secp256k1... yes
configure: secp256k1_CPPFLAGS : -I/usr/local/include
configure: secp256k1_LIBS : -L/usr/local/lib -lsecp256k1
checking whether C++ compiler accepts -std=c++11... yes
checking whether C++ compiler accepts -Wno-deprecated-declarations... yes
checking whether C++ compiler accepts -Wall... yes
checking whether C++ compiler accepts -Wextra... yes
checking whether C++ compiler accepts -Wpedantic... yes
checking whether C++ compiler accepts -Wno-long-long... yes
checking whether C++ compiler accepts -Wno-missing-braces... yes
checking whether the linker accepts -fstack-protector... yes
checking whether the linker accepts -fstack-protector-all... yes
checking whether C++ compiler accepts -fvisibility-hidden... no
checking whether C++ compiler accepts -fvisibility-inlines-hidden... yes
checking whether C++ compiler accepts -fno-var-tracking-assignments... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libbitcoin.pc
config.status: executing depfiles commands
config.status: executing libtool commands

**Comment by evoskuil** [comment]
Thanks, but that much I can assume (since the build completed). It's possible you have a mix of boost versions installed or have a [buggy boost version](https://github.com/boostorg/log/pull/10). Hard to say from configure alone. I'd recommend building using the [install.sh](https://github.com/libbitcoin/libbitcoin/tree/version3#debianubuntu) into a prefix directory, avoiding sudo and building boost. Eg:
```sh
$ ./install.sh --build-boost --prefix=/home/me/myprefix
```

**Comment by evoskuil** [comment]
Hi @ziyoustep, any update?

**Comment by evoskuil** [comment]
Closed for lack of feedback.

**Comment by tzawislak** [comment]
> Thanks, but that much I can assume (since the build completed). It's possible you have a mix of boost versions installed or have a [buggy boost version](https://github.com/boostorg/log/pull/10). Hard to say from configure alone. To verify a baseline I'd recommend building using the [install.sh](https://github.com/libbitcoin/libbitcoin/tree/version3#debianubuntu) into a prefix directory, avoiding sudo and building boost. Eg:
> 
> ```shell
> $ ./install.sh --build-boost --prefix=/home/me/myprefix
> ```

I've encountered the same error while installing libbitcoin and the method mentioned above didn't help. Does anyone know what I should do now?

**Comment by evoskuil** [comment]
Try removing any installations of boost you have on the machine. If you have the same error it’s cross-linking. It does happen with boost. You can also try the static linkage via install.sh.
