### ISSUE TITLE
Adding a new library and then compiling

### ISSUE THREAD

**Issue by nettijoe96** [libbitcoin/libbitcoin#793]
Hi there,

I have been trying to add quantum resistance to the bitcoin core source code. I might switch to libbitcoin code because it is easier to work with. An issue I had with the bitcoin core source was compiling after I added a new directory. I added a new directory of files written in c, called ring-Tesla, but I did not know how to reconfigure and generate the new makefile.am. I would likely have to do the same thing if I switched over to libbitcoin. I am wondering how to generate a new makefile.am. Please keep the answer easy because I am a newbie. This is very frustrating. Thank you for your time. 

Also, I know this may not be the right place to post this, but I am not sure of where else.

**Comment by evoskuil** [comment]
Hi @nettijoe96,

Libbitcoin does not rely on recursive make, as it is a bit of anti-pattern, despite widespread use. The new sources should be referenced directly from the root Makefile.am (and the VS project and filter files). The pattern should be self-explanatory within the Makefile.am.

e

**Comment by evoskuil** [comment]
@nettijoe96 Can this be closed?

**Comment by nettijoe96** [comment]
Yes it can be, sorry I didn't respond earlier. I solved the problem and
then forgot. Thank you again.

Joseph Netti <https://www.linkedin.com/in/joseph-netti-a37a50104>

**Comment by evoskuil** [comment]
NP

**Comment by jonnyhsy** [comment]
For these painful makefile things: does libbitcoin have any plan to support/migrate to use bazel (https://bazel.build/) build system?  It's super developer-friendly and developers doesn't need to figure out makefile black magics. A BUILD file is easy to understand and maintain: https://docs.bazel.build/versions/master/bazel-overview.html

If libbitcoin decides to use bazel we could start a new topic/issue to track this and maybe I could help.

**Comment by evoskuil** [comment]
There is no such plan. All libbitcoin repositories use the custom build generation implemented in [libbitcoin-build](https://github.com/libbitcoin/libbitcoin-build). This supports much more than generation of make files. This has been in place for a couple of years and has been very successful, requiring no manual editing of any build artifacts. You may notice that all libbitcoin build artifacts, Travis files, etc. are generated. However I do not recommend it for a casual PR. Typically maintainers would just re-execute the generation.

As a rule, generalized build systems tend to cause as much complexity as they resolve. However if you would like to create a PR for this support across the 10 libbitcoin repos and for all supported platforms, with support for Travis and AppVeyor CI builds and SWIG templates, we would be very happy to consider it.

**Comment by potadibyo** [comment]
*libbitcoin_util.a(libbitcoin_util_a-util.o): In function

CInit::CInit()': /root/mrcash/src/util.cpp:133: undefined reference to

OPENSSL_init_crypto'
collect2: error: ld returned 1 exit status
Makefile:3661: recipe for target 'mrcashd' failed
make[2]: * mrcashd] Error 1
make[2]: Leaving directory '/root/mrcash/src'
Makefile:9359: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/mrcash/src'
Makefile:741: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by potadibyo** [comment]
any solution to this problem ,
I update openssl version still giving me this error......

**Comment by thecodefactory** [comment]
@potadibyo Your question doesn't appear related to this long closed issue.  Also, OpenSSL is not used or required by libbitcoin.
