### ISSUE TITLE
[VS2015] NuGet packages not found.

### ISSUE THREAD

**Issue by xiongzhend** [libbitcoin/libbitcoin#794]
This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\..\..\..\..\nuget\boost.1.57.0.0\build\native\boost.targets.

**Comment by evoskuil** [comment]
There are currently no VS2015 project files. The automatic upgrade to VS2015 may not work. The nuget packages that are used by the VS2013 project must be located in a relative path outside of the solution directory. This allows the nuget packages to be shared by the multiple libraries.

The [BX readme](https://github.com/libbitcoin/libbitcoin-explorer#windows) provides detailed instructions on setting up the nuget path.

**Comment by evoskuil** [comment]
@xiongzhend can we close this?
