### ISSUE TITLE
Document level of segwit support

### ISSUE THREAD

**Issue by ysangkok** [libbitcoin/libbitcoin#797]
It is not immediately clear to me if segwit is supported, when reading the README. It would be nice to know, especially in a week.

**Comment by skaht** [comment]
Believe SEGWIT is supported. Look at https://coin.dance/nodes and click the "**WHAT IS LIBBBITCOIN**" Button.  Eric, the lead developer, is also a believer in Lightning technology.

**Comment by ysangkok** [comment]
I don't really see how it can be supported, I don't see any mention of it in the code. For example, take a look at [chain/block.cpp](https://github.com/libbitcoin/libbitcoin/blob/master/src/chain/block.cpp). It doesn't mention witnesses.

The pre-segwit transaction serialization format is used in message/block.cpp. But where is the [new one](https://bitcoincore.org/en/segwit_wallet_dev/#transaction-serialization)?

**Comment by evoskuil** [comment]
Segwit change proposals are not implemented. Please see our [policy on forks](https://github.com/libbitcoin/libbitcoin-server/wiki/Frequently-Asked-Questions#consensus).

**Comment by evoskuil** [comment]
@skaht I don't know where that site gets its information, but it doesn't come directly from us.

**Comment by skaht** [comment]
https://medium.com/airbitz/airbitz-and-the-bitcoin-cash-fork-886c62f96d22 talks about BCH/BCC support.
