### ISSUE TITLE
Cannot create Homebrew formula: no tagged release for secp256k1

### ISSUE THREAD

**Issue by sugarjig** [libbitcoin/libbitcoin#802]
This issue is outside of this project's control, but I'm hoping that I can drum up some support to push the right project for a solution. I'm also not able to submit an issue to [libbitcoin/secp256k1](https://github.com/libbitcoin/secp256k1).

## Goal

I'd like to create a Homebrew formula of this project. My ultimate goal was to create one for libbitcoin-explorer, but after following the dependency chain all the way to secp256k1, I realized I couldn't make a formula because it does not have a tagged release. Since a tagged release is a requirement for Homebrew formulae, this means that none of the libbitcoin projects can be installed via Homebrew.

## Purpose

The advantage of creating Homebrew formulae for the libbitcoin projects is making installation of something like libbitcoin-explorer as easy as
```
brew install libbitcoin-explorer
```
The macOS installation instructions for many of the libbitcoin projects already use Homebrew to install dependencies, such as boost. This would take the extra step of making libbitcoin installation trivial.

## Proposed Solution

There is currently a 2 year old open issue for this at https://github.com/bitcoin-core/secp256k1/issues/286. I have to think that this blocks many other Homebrew formulae from being created, if they want to depend on secp256k1. **I'm requesting that if others are interested in Homebrew formulae for libbitcoin projects, they bump the thread to create a tagged release.** I hope this gets their attention, but I'm not 100% certain it will.

Alternatively, there is an unofficial tap at https://github.com/DomT4/homebrew-crypto, but I thought it best to avoid using it when submitting a formula to the official Homebrew repo.

**Comment by evoskuil** [comment]
Hello @sugarjig,

It is due to secp256k1 version ambiguity that we maintain a [fork of that repository](https://github.com/libbitcoin/secp256k1). I can tag that fork if it helps.

**Comment by sugarjig** [comment]
Hi @evoskuil! I considered suggesting that. That would solve the immediate problem. Will it cause a problem if the source project starts tagging their versions?

**Comment by evoskuil** [comment]
I don't think so.

**Comment by evoskuil** [comment]
Tag added: https://github.com/libbitcoin/secp256k1/tags

**Comment by sugarjig** [comment]
Thanks! I'll get to work adding it to Homebrew.
