### ISSUE TITLE
Undefined reference to boost

### ISSUE THREAD

**Issue by mounibec** [libbitcoin/libbitcoin#805]
I'm trying to run a simple program that includes libbitcoin and I get this error when compiling:

```
g++-4.8 -std=c++11 -I /usr/include/boost/include -o hello hello.cpp
/tmp/cczhQ2e3.o: In function `__static_initialization_and_destruction_0(int, int)':
hello.cpp:(.text+0x5f): undefined reference to `boost::system::generic_category()'
hello.cpp:(.text+0x6b): undefined reference to `boost::system::generic_category()'
hello.cpp:(.text+0x77): undefined reference to `boost::system::system_category()'
hello.cpp:(.text+0xb5): undefined reference to `libbitcoin::config::checkpoint::checkpoint(std::string const&, unsigned long)'
hello.cpp:(.text+0x104): undefined reference to `libbitcoin::config::checkpoint::checkpoint(std::string const&, unsigned long)'
hello.cpp:(.text+0x153): undefined reference to `libbitcoin::config::checkpoint::checkpoint(std::string const&, unsigned long)'
hello.cpp:(.text+0x1a2): undefined reference to `libbitcoin::config::checkpoint::checkpoint(std::string const&, unsigned long)'
hello.cpp:(.text+0x1f1): undefined reference to `libbitcoin::config::checkpoint::checkpoint(std::string const&, unsigned long)'
/tmp/cczhQ2e3.o:hello.cpp:(.text+0x240): more undefined references to `libbitcoin::config::checkpoint::checkpoint(std::string const&, unsigned long)' follow
/tmp/cczhQ2e3.o: In function `__static_initialization_and_destruction_0(int, int)':
hello.cpp:(.text+0x318): undefined reference to `libbitcoin::machine::number::negative_mask'
/tmp/cczhQ2e3.o: In function `boost::asio::error::get_system_category()':
hello.cpp:(.text._ZN5boost4asio5error19get_system_categoryEv[_ZN5boost4asio5error19get_system_categoryEv]+0x5): undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status
```
I use Ubuntu 16.04.3, and followed install instructions in the README of https://github.com/libbitcoin/libbitcoin. 

I installed libbitcoin using `sudo ./install.sh --build-boost --prefix=/usr/include/boost` but boost path isn't apparently recognised when compiling hello.cpp.

The program is:
```
#include <iostream>
#include <bitcoin/bitcoin.hpp>

int main() {
  std::cout << "Hello Bitcoin";
}
```
Am I missing something ?

Thanks in advance

**Comment by evoskuil** [comment]
Not sure, if you could post the full build output it would help. You might use a non-system directory and avoid sudo. Don't know what is in that path.

**Comment by evoskuil** [comment]
Hi @mounibec, any update?

**Comment by mounibec** [comment]
I'll try again and let you know

**Comment by mounibec** [comment]
I tried again by re-installing boost and libbitcoin but got the same error. Here is the build log

[install.log](https://github.com/libbitcoin/libbitcoin/files/1377456/install.log)

**Comment by pmienk** [comment]
Your log indicates successful libbitcoin compilation and installation.  Your issue is your own incorrect linking as described above.  Specifically, you are failing to provide the prefix location to your compilation statement in the form of a `-L` argument to `g++`.

**Comment by mounibec** [comment]
Thanks @pmienk. I tried the -L parameter but still failing with the same error or I misunderstand your response. 

`
$ g++ -std=c++11 -L /usr/include/boost/lib -o hello hello.cpp

/tmp/ccJtUrUu.o: In function `__static_initialization_and_destruction_0(int, int)':
hello.cpp:(.text+0x6e): undefined reference to `boost::system::generic_category()'
hello.cpp:(.text+0x7a): undefined reference to `boost::system::generic_category()'
hello.cpp:(.text+0x86): undefined reference to `boost::system::system_category()'
hello.cpp:(.text+0xc4): undefined reference to `libbitcoin::config::checkpoint::checkpoint(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)'
hello.cpp:(.text+0x113): undefined reference to `libbitcoin::config::checkpoint::checkpoint(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)'
hello.cpp:(.text+0x162): undefined reference to `libbitcoin::config::checkpoint::checkpoint(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)'
hello.cpp:(.text+0x1b1): undefined reference to `libbitcoin::config::checkpoint::checkpoint(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)'
hello.cpp:(.text+0x200): undefined reference to `libbitcoin::config::checkpoint::checkpoint(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)'
/tmp/ccJtUrUu.o:hello.cpp:(.text+0x24f): more undefined references to `libbitcoin::config::checkpoint::checkpoint(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)' follow
/tmp/ccJtUrUu.o: In function `__static_initialization_and_destruction_0(int, int)':
hello.cpp:(.text+0x327): undefined reference to `libbitcoin::machine::number::negative_mask'
/tmp/ccJtUrUu.o: In function `boost::asio::error::get_system_category()':
hello.cpp:(.text._ZN5boost4asio5error19get_system_categoryEv[_ZN5boost4asio5error19get_system_categoryEv]+0x5): undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status`

and if I do:
`
$ ls /usr/include/boost/lib

libbitcoin.a                  libboost_filesystem.a          libboost_log_setup.so                libboost_regex.so                libboost_unit_test_framework.so.1.57.0
libbitcoin.la                 libboost_filesystem.so         libboost_log_setup.so.1.57.0         libboost_regex.so.1.57.0         libsecp256k1.a
libbitcoin.so                 libboost_filesystem.so.1.57.0  libboost_log.so                      libboost_system.a                libsecp256k1.la
libbitcoin.so.0               libboost_iostreams.a           libboost_log.so.1.57.0               libboost_system.so               libsecp256k1.so
libbitcoin.so.0.0.0           libboost_iostreams.so          libboost_prg_exec_monitor.a          libboost_system.so.1.57.0        libsecp256k1.so.0
libboost_chrono.a             libboost_iostreams.so.1.57.0   libboost_prg_exec_monitor.so         libboost_test_exec_monitor.a     libsecp256k1.so.0.0.0
libboost_chrono.so            libboost_locale.a              libboost_prg_exec_monitor.so.1.57.0  libboost_thread.a                pkgconfig
libboost_chrono.so.1.57.0     libboost_locale.so             libboost_program_options.a           libboost_thread.so
libboost_date_time.a          libboost_locale.so.1.57.0      libboost_program_options.so          libboost_thread.so.1.57.0
libboost_date_time.so         libboost_log.a                 libboost_program_options.so.1.57.0   libboost_unit_test_framework.a
libboost_date_time.so.1.57.0  libboost_log_setup.a           libboost_regex.a                     libboost_unit_test_framework.so`

**Comment by mounibec** [comment]
Found it, it was a issue linking -lboost_system, so I created a symbolic link:

`sudo ln -s /usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0 /usr/lib/libboost_system.so`

Thanks for your help anyway.

**Comment by evoskuil** [comment]
Don't use a libbitcoin prefix directory that is a subdirectory of the boost include directory. Build with a prefix directory that is not a /usr/ subdirectory.

**Comment by pmienk** [comment]
@evoskuil makes a good point - the location you're using as prefix is misleading to the normal conventions, as you're placing libs within an includes directory.

Also, you'll want to include all the pkgconfig includes and libs to avoid these issues in future.  You'll get a lot of mileage out of autoconf/automake as they will pull in the appropriate information from pkgconfig.

**Comment by mounibec** [comment]
Like this ./install.sh --build-boost --prefix=/home/me/btc ?

**Comment by pmienk** [comment]
That would be better in that it isn't exposing your private installation to the rest of the system.  Additionally, when you invoke the compiler you should add arguments resulting from

```
PKG_CONFIG_PATH=<prefix>/lib/pkgconfig pkg-config --cflags --libs <library>
```

which in your above case would be

```
PKG_CONFIG_PATH=/home/me/btc/lib/pkgconfig pkg-config --cflags --libs libbitcoin
```

and would result in something like

```
-I/home/me/btc/include -L/home/me/btc/lib -lbitcoin -lboost_chrono -lboost_date_time -lboost_filesystem -lboost_iostreams -lboost_locale -lboost_log -lboost_program_options -lboost_regex -lboost_system -lboost_thread -lpthread -lrt -ldl -lsecp256k1
```

**Comment by mounibec** [comment]
I tried this methods but I still got the same errors.

But it worked fine after switching to g++5 as recommended by @michel-foucault.

Thanks guys for your time and help !

**Comment by michel-foucault** [comment]
Perhaps the documentation could be updated for ubuntu 16

Log for using libbitcoin on ubuntu 16.04:
`#setup
sudo apt-get install -y build-essential autoconf automake libtool pkg-config git libboost-all-dev
wget https://raw.githubusercontent.com/libbitcoin/libbitcoin/version3/install.sh
chmod +x install.sh
sudo ./install.sh
#build
g++ -std=c++11 hello.cpp -lpthread -lboost_chrono -lboost_date_time -lboost_filesystem -lboost_iostreams -lboost_locale -lboost_log -lboost_program_options -lboost_regex -lboost_system -lboost_thread -lsecp256k1 -lbitcoin -o hello
`

**Comment by pmienk** [comment]
@mounibec, @michel-foucault if your issues are boost related, did either of you try a prefix install with the build-boost option so as to build the minimum version of boost supported by libbitcoin without a installation collision with the package delivered version?

**Comment by mounibec** [comment]
Yeah I did using  ./install.sh --build-boost --prefix=/home/me/btc

**Comment by pmienk** [comment]
@mounibec, you also had a successful installation as indicated by the log above.  In addition, the initial issue explicitly uses g++ 4.8.  Is this because g++ 5.0 was used in all installations?

I'm not sure your issue is related to that of @michel-foucault.  His issue may be resolved by prefixed installation and install.an driven boost build.

**Comment by mounibec** [comment]
I didn't have g++ 5 before, but I installed it and re-installed libboost 1.58.0 (using apt-get), then re-installed libbitcoin (without --build-boost option).

For compiling, I still need to link libbitoin and boost:

`g++ -std=c++11 hello.cpp -lboost_system -lbitcoin -o hello`

**Comment by pmienk** [comment]
@mounibec, currently my understanding of this issue is as follows:

On Ubuntu 16.04.3 ([which appears to default gcc/g++compilers to version >= 5.0](https://packages.ubuntu.com/xenial/g++))

1)  g++4.8 was installed
2) install.sh was invoked successfully with --build-boost argument and prefix.
3) manual g++ invocation produced error, presumably due to unspecified libraries.
4) g++5 was installed.
5) install.sh was re-executed without --build-boost in a presumed clean prefix.
6) manual g++ invocation was successful with a subset of the libraries expressed in the package config file.

The above is my best understanding after having reread this thread.  If the above is accurate, I assume that g++5 or not, an install.sh invocation with --build-boost argument would have produced a successful manual g++ invocation so long as the package configuration data was provided.

I would expect failure of a combination of g++4.8 and the Ubuntu 16.04.3 libboost-dev-all package due to the fact that Ubuntu's default compilers appear to me to be [5.0 or above](https://packages.ubuntu.com/xenial/g++).  I presume packages are delivered having been compiled with the default compiler and that an [ABI incompatibility](https://stackoverflow.com/questions/34974854/undefined-reference-when-linking-with-boost-using-g-4-9-on-a-g-5-ish-distrib) similar to the one linked is responsible for the misbehavior.  Additionally, the use of g++5.0 would explain the absence of the incompatibility and the successful linking with the package.

**Comment by mounibec** [comment]
@pmienk Yes this is a perfect recap.

**Comment by evoskuil** [comment]
Thanks @pmienk for the clear explanation. I think we can close this as correct behavior in all cases.
