### ISSUE TITLE
build error: undefined reference to `secp256k1_ecdsa_recover'

### ISSUE THREAD

**Issue by zhou0** [libbitcoin/libbitcoin#807]
CXX      examples/examples_libbitcoin_examples-main.o
  CXXLD    examples/libbitcoin_examples
src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recover'
src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_sign_recoverable'
src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recoverable_signature_serialize_compact'
src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recoverable_signature_parse_compact'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
*** Error code 1

Stop.
make: stopped in /usr/home/lzhou/github.com/libbitcoin/libbitcoin/archive/libbitcoin-3.3.0

**Comment by evoskuil** [comment]
When not using the install script you must make sure to build libsecp256k1 with the necessary options (which I don't recall ATM, traveling) and use a compatible version (the library is not versioned, which is why we maintain a fork).

**Comment by zhou0** [comment]
I forget to add "--enable-module-recovery" flag while configuring libsecp256k1.   Error is gone after rebuilding it with this flag.
