### ISSUE TITLE
No package 'libbitcoin' found

### ISSUE THREAD

**Issue by CryptoCoding** [libbitcoin/libbitcoin#808]
I am trying to run this command from the _Mastering Bitcoin_ book `g++ -o addr addr.cpp $(pkg-config --cflags --libs libbitcoin)`

I then get this 
```
Package libbitcoin was not found in the pkg-config search path.
Perhaps you should add the directory containing `libbitcoin.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libbitcoin' found
```

and I do this 

`PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/Users/joshuastern/Desktop/mastering_bitcoin/libbitcoin/build-libbitcoin/libbitcoin/libbitcoin.pc`

But I still get this 

```
Package libbitcoin was not found in the pkg-config search path.
Perhaps you should add the directory containing `libbitcoin.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libbitcoin' found
```

If anyone knows how to fix this please help me!

**Comment by thecodefactory** [comment]
@CryptoCoding Hopefully you've been able to resolve this, but what you need to do is this (assuming you're using the bash shell):

```
export PKG_CONFIG_PATH=/path/to/libbitcoin-installation/lib/pkgconfig
```

**Comment by hilalh** [comment]
Please include the `-std=c++11` flag on OS X
