### ISSUE TITLE
libsecp256k1 references libbitcoin_examples

### ISSUE THREAD

**Issue by mikewerwin** [libbitcoin/libbitcoin#809]
Howdy,

I'm hoping you guys can give me a little nudge in the right direction in building libbitcoin. 

As a prerequisite, I built and installed secp256k1 (default target to: /usr/local/lib) from:
`git clone https://github.com/libbitcoin/secp256k1.git`

I then ran `configure`, which required that I tweak the path:
`./configure PKG_CONFIG_PATH="/usr/local/lib/pkgconfig/"`

Make worked as expected, until `libbitcoin_examples` here:
```
<snip> 
  CXX      src/wallet/parse_encrypted_keys/src_libbitcoin_la-parse_encrypted_token.lo
  CXX      examples/examples_libbitcoin_examples-main.o
  CXXLD    src/libbitcoin.la
copying selected object files to avoid basename conflicts...
  CXXLD    examples/libbitcoin_examples
src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recover'
src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_sign_recoverable'
src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recoverable_signature_serialize_compact'
src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recoverable_signature_parse_compact'
collect2: error: ld returned 1 exit status
make: *** [examples/libbitcoin_examples] Error 1
```

Any help would be much appreciated!
-ME

**Comment by evoskuil** [comment]
When building libsecp you must use the --enable-module-recovery option. The libbitcoin install.sh does this internally. See the libbitcoin readme.

**Comment by skaht** [comment]
The bottom of https://github.com/libbitcoin/libbitcoin/issues/396 is a bit dated. The key point is that the install.sh files tend to automatically download, configure, build and install executables as needed. Examine the install.sh scripts for additional flags as needed.

**Comment by evoskuil** [comment]
This particular flag is also documented independently in the libbitcoin readme, as it is a common mistake when building independently.

**Comment by mikewerwin** [comment]
Much apologies. I should have paid more attention to the docs. Thanks for the explanation.

**Comment by evoskuil** [comment]
No problem.

**Comment by ricardofriba** [comment]
dude, you save my live..

Thank you very much!!
