### ISSUE TITLE
OSX: Travis homebrew failure due to ruby version.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin#812]
/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)

https://travis-ci.org/libbitcoin/libbitcoin/jobs/289562632

**Comment by pmienk** [comment]
Addressed by libbitcoin/libbitcoin#815 for this repo, fixed in generation of artifacts libbitcoin/libbitcoin-build#103 and similar pull requests for all other repos.
