### ISSUE TITLE
script::is_pay_multisig_pattern off-by-one error

### ISSUE THREAD

**Issue by DanielKrawisz** [libbitcoin/libbitcoin#814]
The function is supposed to identify patterns like this 

m (sequence of n pubkeys...) n op_checkmultisig

but instead matches this

m (sequence of n + 1 pubkeys) n op_checkmultisig

Fixed in https://github.com/libbitcoin/libbitcoin/pull/811

**Comment by evoskuil** [comment]
Thanks @DanielKrawisz!

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin/pull/811 requires backport to 3.x

**Comment by evoskuil** [comment]
Backported for v3.4.
