### ISSUE TITLE
Official website - https://libbitcoin.org/ is not working

### ISSUE THREAD

**Issue by bitcoinextw** [libbitcoin/libbitcoin#818]
Hi, the Official website has been inaccessible for 3 days already. No one noticed that?

**Comment by evoskuil** [comment]
Yes

**Comment by evoskuil** [comment]
The domain is not under the control of any current dev. I believe @phantomcircuit owns it.

**Comment by bitcoinextw** [comment]
Alright. Could you suggest me anywhere else I can see like API documents or something about how to use these libraries in detail?
Thank you very much.

**Comment by evoskuil** [comment]
libbitcoin.org does not provide any documentation, everything current is available on github on the wikis for the respective repositories. [Server](https://github.com/libbitcoin/libbitcoin-server/wiki) and [Explorer](https://github.com/libbitcoin/libbitcoin-explorer/wiki) have a good amount of information. [Libbitcoin (system)](https://github.com/libbitcoin/libbitcoin/wiki) has a limited amount. There is also an external reference at the [bitcoin wiki](https://en.bitcoin.it/wiki/Libbitcoin), and [tutorials here](http://aaronjaramillo.org/category/libbitcoindocs).

**Comment by bitcoinextw** [comment]
ohhh okay. Didn't have a chance to read the content of libbitcoin.org. 
Thank you for the information. 
What about if these set of libraries are platform independent, one version can be executed in Windows, Linux?

**Comment by evoskuil** [comment]
NP. I'm documented the down side in the website repo. Someone is working it presently. The libraries are supported and regularly built and tested on Linux, macOS and Windows.

**Comment by evoskuil** [comment]
Moved to https://github.com/libbitcoin/libbitcoin.github.io/issues/5
