### ISSUE TITLE
Hi，I was going to build libbitcoin in Ubuntu, and errors be found

### ISSUE THREAD

**Issue by silravend** [libbitcoin/libbitcoin#832]
I was following the instruction like:
$ g++ --version
>g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
>Copyright (C) 2015 Free Software Foundation, Inc.
>This is free software; see the source for copying conditions.  There is NO
>warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ sudo apt-get install build-essential autoconf automake libtool pkg-config git

$ sudo apt-get install libboost-all-dev

$ wget https://raw.githubusercontent.com/libbitcoin/libbitcoin/version3/install.sh
$ chmod +x install.sh

$ sudo ./install.sh

then I got this:

g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:3203: recipe for target 'src/log/src_libbitcoin_la-sink.lo' failed
make: *** [src/log/src_libbitcoin_la-sink.lo] Error 1

**Comment by silravend** [comment]
And then I tried to change to 4.8.5
$ sudo apt-get install g++-4.8
$ sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50
$ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
$ sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 50

then it take a long long time at this line:
>src/log/src_libbitcoin_la-sink.lo

Anyone meet this? How do I fix it?

**Comment by silravend** [comment]
And then I tried on my virtual machine, errors as follow:

src/.libs/libbitcoin.so: undefined reference to `boost::log::v2_mt_posix::sinks::text_file_backend::consume(boost::log::v2_mt_posix::record_view const&, std::string const&)'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::to_internal(std::string const&)'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::option_description::long_name() const'
src/.libs/libbitcoin.so: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > > > const&)'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::option_description::format_name() const'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
src/.libs/libbitcoin.so: undefined reference to `boost::log::v2_mt_posix::aux::code_convert(wchar_t const*, unsigned long, std::string&, std::locale const&)'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::option_description::format_parameter() const'
src/.libs/libbitcoin.so: undefined reference to `boost::log::v2_mt_posix::sinks::basic_text_ostream_backend<char>::consume(boost::log::v2_mt_posix::record_view const&, std::string const&)'
src/.libs/libbitcoin.so: undefined reference to `boost::filesystem::path_traits::dispatch(boost::filesystem::directory_entry const&, std::string&)'
src/.libs/libbitcoin.so: undefined reference to `boost::re_detail::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::string>, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::string> > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::positional_options_description::name_for_position(unsigned int) const'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
src/.libs/libbitcoin.so: undefined reference to `void boost::log::v2_mt_posix::aux::put_integer<char>(std::basic_string<char, std::char_traits<char>, std::allocator<char> >&, unsigned int, unsigned int, char)'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::option_description::description() const'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
src/.libs/libbitcoin.so: undefined reference to `boost::program_options::parse_environment(boost::program_options::options_description const&, std::string const&)'
collect2: error: ld returned 1 exit status
Makefile:2197: recipe for target 'examples/libbitcoin_examples' failed
make: *** [examples/libbitcoin_examples] Error 1

**Comment by evoskuil** [comment]
You are missing boost program options.

**Comment by silravend** [comment]
Thanks bro, problem fixed
