### ISSUE TITLE
Readme and Github License contradict

### ISSUE THREAD

**Issue by n1rvana** [libbitcoin/libbitcoin#840]
In the repo, if you click on the license button ("agpl-3.0") you see the summary:
"Permissions of this strongest copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license."

Meanwhile the readme indicates that the license enables use in closed source work so long as the library and and modifications to it are published.

The readme terms are fine, but the license seems to state otherwise (And the purpose of affero GPL IIRC was to make it even more viral.)

I'm guessing the wrong license was chosen in the github settings for the project.

**Comment by evoskuil** [comment]
The license is [here](https://github.com/libbitcoin/libbitcoin/blob/master/COPYING), and summarized by GitHub as follows:

> Permissions of this strongest copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.

The [readme](https://github.com/libbitcoin/libbitcoin/blob/master/README.md) license summary states:

> All files in this repository fall under the license specified in COPYING. The project is licensed as AGPL with a lesser clause. It may be used within a proprietary project, but the core library and any changes to it must be published online. Source code for this library must always remain free for everybody to access.

The readme summary is not in conflict with the AGPLv3.
