### ISSUE TITLE
Community servers not current.

### ISSUE THREAD

**Issue by 15963** [libbitcoin/libbitcoin#869]
I query the height of the block yesterday,use bx fetch-height.

demo:
bx fetch-height
487000

Is there a problem with the server？？？
url is url=tcp://mainnet.libbitcoin.net:9091。

**Comment by evoskuil** [comment]
Yes, the servers were misconfigured. Mainnet is being resynced and testnet is being looked at more closely to ensure there was no other issue.

**Comment by 15963** [comment]
wo use bx fetch-height today.

demo:
bx fetch-height
457083

Why less and less??? The last time was 487000

**Comment by evoskuil** [comment]
> Mainnet is being resynced

**Comment by evoskuil** [comment]
```
$ bx fetch-height tcp://mainnet.libbitcoin.net:9091
501655

$ bx fetch-height tcp://testnet.libbitcoin.net:19091
1256747
```

**Comment by evoskuil** [comment]
The default servers are now current, however they will be resynced again shortly. We'll see if we can't maintain server during the update, but with only one set of servers presently it's more of a challenge.
