### ISSUE TITLE
WITH_ICU inconsistency in wallet::encrypted_keys

### ISSUE THREAD

**Issue by cryptogopher** [libbitcoin/libbitcoin#885]
There is a mismatch between sets of functions included in
```
#ifdef WITH_ICU
#endif
```
clauses between wallet/encrypted_keys.hpp and wallet/encrypted_keys.cpp resulting in a linking error for build without ICU:
```
libbitcoin_wrap.cxx:(.text+0xca5a): undefined reference to `libbitcoin::wallet::create_token(std::array<unsigned char, 53ul>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::array<unsigned char, 4ul> const&, unsigned int, unsigned int)'
libbitcoin_wrap.cxx:(.text+0xcb9b): undefined reference to `libbitcoin::wallet::create_token(std::array<unsigned char, 53ul>&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::array<unsigned char, 8ul> const&)'
```

I'm not sure which of those 2 sets is proper, so don't have patch.

**Comment by evoskuil** [comment]
The `--without-icu` builds are [successful](https://travis-ci.org/libbitcoin/libbitcoin/jobs/325693130) in Travis, and neither `create_token` function is wrapped by a `WITH_ICU` condition, in either the header or implementation

**Comment by evoskuil** [comment]
The Travis builds are [successful](https://travis-ci.org/libbitcoin/libbitcoin/jobs/325693130) but I can see from the sources that these two functions are not conditionally excluded in the header as they should be.

**Comment by evoskuil** [comment]
This is resolved in the above master PR and backported to the head of version3. Thanks for reporting!
