### ISSUE TITLE
could not build libbitcoin-examples with symbol already defined at Visual Studio 2017

### ISSUE THREAD

**Issue by ron-lee** [libbitcoin/libbitcoin#888]
Hello Expert, 

I am able to build the libbitcoin by itself, however I am able to build the libbitcoin-examples, here is the error I saw:

`2>libboost_regex-vc141-mt-sgd-1_64.lib(instances.obj) : error LNK2005: "private: class boost::basic_regex<char,struct boost::regex_traits<char,class boost::w32_regex_traits<char> > > & __thiscall boost::basic_regex<char,struct boost::regex_traits<char,class boost::w32_regex_traits<char> > >::do_assign(char const *,char const *,unsigned int)" (?do_assign@?$basic_regex@DU?$regex_traits@DV?$w32_regex_traits@D@boost@@@boost@@@boost@@AAEAAV12@PBD0I@Z) already defined in boost_regex-vc140-mt-gd.lib(boost_regex-vc141-mt-gd-x32-1_66.dll)
2>D:\Personal\libbitcoin\builds\msvc\vs2017\libbitcoin-examples\..\..\..\..\bin\Win32\Debug\v141\static\libbitcoin-examples.exe : fatal error LNK1169: one or more multiply defined symbols found
`

Any idea? I do see 2 of such errors.  

I downloaded both dynamics and static libraries for boost via vcpkg.  After some internet search and not sure what I should do to fix this. 

Thanks very much in advance, 

Ron.

**Comment by evoskuil** [comment]
As can be seen form the error message you are linking to two different boost libs:

boost_regex-vc140-mt-gd.lib
libboost_regex-vc141-mt-sgd-1_64.lib

I recommend building using the steps documented in the readme.

**Comment by ron-lee** [comment]
Thanks, it looks libraries from vcpkg are mixed up with packages from nuget. I am able to build after removed vcpkg integration with visual studio.  thanks again.
