### ISSUE TITLE
Include libbitcoin in other projects Visual Studio 2017

### ISSUE THREAD

**Issue by MrBeingMan** [libbitcoin/libbitcoin#900]
I was able to successfully build the libbitcoin using visual studio 2017 and I was just wonder how I can now use the libbitcoin.lib in other projects. When I try to add it to different projects I get a lot of errors which I am unable to solve.

I was wondering if anyone could give me a step by step on how to link the library into other projects thank you.

**Comment by evoskuil** [comment]
You could use its inclusion in other libbitcoin projects as an example.

**Comment by MrBeingMan** [comment]
I get these errors when I include it into a project

`1> packages\boost.1.64.0.0\lib\native\include\boost/typeof/msvc/typeof_impl.hpp(125): error C2988: unrecognizable template declaration/definition
1> packages\boost.1.64.0.0\lib\native\include\boost/typeof/msvc/typeof_impl.hpp(133): note: see reference to class template instantiation 'boost::type_of::msvc_extract_type<ID,T>' being compiled
1> packages\boost.1.64.0.0\lib\native\include\boost/typeof/msvc/typeof_impl.hpp(125): error C2143: syntax error: missing ';' before '<'
1> packages\boost.1.64.0.0\lib\native\include\boost/typeof/msvc/typeof_impl.hpp(125): error C2913: explicit specialization; 'boost::type_of::id2type_impl' is not a specialization of a class template
1> packages\boost.1.64.0.0\lib\native\include\boost/typeof/msvc/typeof_impl.hpp(125): error C2059: syntax error: '<'
1> packages\boost.1.64.0.0\lib\native\include\boost/typeof/msvc/typeof_impl.hpp(126): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1> packages\boost.1.64.0.0\lib\native\include\boost/scope_exit.hpp(419): error C2988: unrecognizable template declaration/definition
1> packages\boost.1.64.0.0\lib\native\include\boost/scope_exit.hpp(427): note: see reference to class template instantiation 'boost::scope_exit::aux::msvc_typeof_this::msvc_extract_type<ID,T>' being compiled
1> packages\boost.1.64.0.0\lib\native\include\boost/scope_exit.hpp(419): error C2143: syntax error: missing ';' before '<'
1> packages\boost.1.64.0.0\lib\native\include\boost/scope_exit.hpp(419): error C2913: explicit specialization; 'boost::scope_exit::aux::msvc_typeof_this::id2type_impl' is not a specialization of a class template
1> packages\boost.1.64.0.0\lib\native\include\boost/scope_exit.hpp(419): error C2059: syntax error: '<'`

**Comment by evoskuil** [comment]
I recommend you take the libbitcoin example project and modify it for your use.

**Comment by MrBeingMan** [comment]
Okay I will give it a go. Thank you
