### ISSUE TITLE
G++ can not access libbitcoin in my APP

### ISSUE THREAD

**Issue by mddia** [libbitcoin/libbitcoin#921]
I have installed libbitcoin on ubuntu 16 as it is described in the documentation. All worked fine.

Bu when I try to complie my own source file:
 g++ -std=c++11 -lbitcoin  -o first main.cpp $(pkg-config --cflags  --libs libbitcoin)

I am getting this error:
```
 error: ‘block_type’ was not declared in this scope                                                                                                                                                            
     block_type blk = genesis_block();
```
here is my source code:

`#include <bitcoin/bitcoin.hpp>
#include <iostream>

using namespace std;
using namespace std;

/*
 * 
 */
int main(int argc, char** argv) {

    block_type blk = genesis_block();
    std::cout << encode_hex(hash_block_header(blk.header)) << std::endl;
    return 0;
}`

Thank you. I am just beginning

**Comment by thecodefactory** [comment]
@mddia Welcome!  There are some problems with your code, and it seems like you're basing it from an older version, or outdated documentation?  Using the current master branch (the latest code), you could do something like this:

```
#include <bitcoin/bitcoin.hpp>

using namespace bc;

int main(int argc, char** argv)
{
    chain::block blk = chain::block::genesis_mainnet();
    std::cout << encode_base16(blk.header().hash()) << std::endl;
    return 0;
}
```

**Comment by mddia** [comment]
wow, I have really an outdated version. You save me @thecodefactory 
thank you

**Comment by thecodefactory** [comment]
@mddia Oh yes, that is very outdated at this point! It is for libbitcoin version1.  These repos contain v2, v3, and the master branch is currently the v4 work in progress.

One of the best places to learn and see how libbitcoin can be used (other than in libbitcoin source itself) is in the explorer project:

https://github.com/libbitcoin/libbitcoin-explorer/tree/master/src/commands

Which corresponds to the commands described here:

https://github.com/libbitcoin/libbitcoin-explorer/wiki

**Comment by mddia** [comment]
Thanks @thecodefactory
