### ISSUE TITLE
Can't locate a definition of a method !

### ISSUE THREAD

**Issue by mddia** [libbitcoin/libbitcoin#927]
This is not an issue. It's rather a question about c++ (on libbitcoin). Since the documentation is outdated, I would like to contribute to its update.

Here is a snippet of code witch works well. I have installed -client, -explorer, -protocole.

` 
void getBalance(wallet::payment_address address) {
    client::connection_type connection = {};
    connection.retries = 3;
    connection.timeout_seconds = 8;
    connection.server = config::endpoint("tcp://mainnet.libbitcoin.net:9091")

    client::obelisk_client o_client(connection);

    static const auto on_done = [](const chain::history::list & rows) {
        uint64_t balance = balancer(rows);
        std::cout << encode_base10(balance, 8) << std::endl;

    };
    static const auto on_error2 = [](const code ec) {

        std::cout << "Error Code: " << ec.message() << std::endl;

    };

    if (!o_client.connect(connection)) {
        std::cout << "Fail" << std::endl;
    } else {
        std::cout << "Connection Succeeded" << std::endl;
    }

    o_client.blockchain_fetch_history3(on_error2, on_done, address);
    o_client.wait();
}`

My question is about blockchain_fetch_history3 method. Where it is declared in client::obelisk_client context ? I have found it in fetch_balance, proxy etc. But I can't see its declaration or definition in client::obelisk_client context.

Thank you

**Comment by evoskuil** [comment]
> Since the documentation is outdated

Link?

**Comment by thecodefactory** [comment]
@evoskuil Maybe I closed this too soon, but @mddia entered an issue somewhat recently referring to libbitcoin v1 documentation from libbitcoin.dyne.org, so I had assumed that's what was being referenced from the start as outdated.

**Comment by mddia** [comment]
@evoskuil https://libbitcoin.dyne.org/doc/quickstart.html
