### ISSUE TITLE
Libbitcoin-networks requires libbitcoin version  4.0.0

### ISSUE THREAD

**Issue by mddia** [libbitcoin/libbitcoin#934]
I thought the actual version of lib bitcoin core is 3. I have the 3.4.0 version installed;
I tried to install libbitcoin-network, here is the error I have

configure: error: Package requirements (libbitcoin >= 4.0.0) were not met:

is there a way to update ?

**Comment by thecodefactory** [comment]
@mddia The current production code is version3 (in the version3 branch on each repo).

Version4 is the master branch and is not released/tagged yet because it's not quite ready yet.  I recommend using the version3 branches/installers.

**Comment by mddia** [comment]
thanks
