### ISSUE TITLE
What extra configurations are needed to use the liblibbitcoin.lib?

### ISSUE THREAD

**Issue by GingerMoon** [libbitcoin/libbitcoin#938]
I tried to create a brand new helloworld project to use liblibbitcoin.lib.
I have already done some configurations, including setting the include path, the lib's path, some Preprocessor Definitions. However, I am still stuck by the errors below.

I wonder if there is a clear document telling users what kind of configuration which is needed to use the lib. For example, the include path, the lib directory, the Preprocessor Definitions, and maybe some more. 

Errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2988	unrecognizable template declaration/definition	libtest	c:\cppworkspace\.nuget\packages\boost.1.64.0.0\lib\native\include\boost\typeof\msvc\typeof_impl.hpp	125	
Error	C2143	syntax error: missing ';' before '<'	libtest	c:\cppworkspace\.nuget\packages\boost.1.64.0.0\lib\native\include\boost\typeof\msvc\typeof_impl.hpp	125	
Error	C2913	explicit specialization; 'boost::type_of::id2type_impl' is not a specialization of a class template	libtest	c:\cppworkspace\.nuget\packages\boost.1.64.0.0\lib\native\include\boost\typeof\msvc\typeof_impl.hpp	125	
Error	C2059	syntax error: '<'	libtest	c:\cppworkspace\.nuget\packages\boost.1.64.0.0\lib\native\include\boost\typeof\msvc\typeof_impl.hpp	125	
Error	C2334	unexpected token(s) preceding '{'; skipping apparent function body	libtest	c:\cppworkspace\.nuget\packages\boost.1.64.0.0\lib\native\include\boost\typeof\msvc\typeof_impl.hpp	126	
Error	C2988	unrecognizable template declaration/definition	libtest	c:\cppworkspace\.nuget\packages\boost.1.64.0.0\lib\native\include\boost\scope_exit.hpp	419	
Error	C2143	syntax error: missing ';' before '<'	libtest	c:\cppworkspace\.nuget\packages\boost.1.64.0.0\lib\native\include\boost\scope_exit.hpp	419	
Error	C2913	explicit specialization; 'boost::scope_exit::aux::msvc_typeof_this::id2type_impl' is not a specialization of a class template	libtest	c:\cppworkspace\.nuget\packages\boost.1.64.0.0\lib\native\include\boost\scope_exit.hpp	419	
Error	C2059	syntax error: '<'	libtest	c:\cppworkspace\.nuget\packages\boost.1.64.0.0\lib\native\include\boost\scope_exit.hpp	419	
Error	C2334	unexpected token(s) preceding '{'; skipping apparent function body	libtest	c:\cppworkspace\.nuget\packages\boost.1.64.0.0\lib\native\include\boost\scope_exit.hpp	419	
Error	C4996	'localtime': This function or variable may be unsafe. Consider using localtime_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	libtest	c:\cppworkspace\libbitcoin\include\bitcoin\bitcoin\utility\timer.hpp	48

**Comment by evoskuil** [comment]
The import properties files should be used by a dependent project in the same manner as they are used in library dependent projects.

**Comment by GingerMoon** [comment]
Hi @evoskuil 
Thank you very much for your reply!
I need to use the lib in Qt.  I will try to understand the properties files and do the necessary configuration manually in Qt.

**Comment by GingerMoon** [comment]
Hi @evoskuil 
Many thanks for the information.

The link errors in the Qt look like below (the libbitcoin.lib was built with the default options):

libbitcoin.lib(checkpoint.obj):-1: error: LNK2038: 检测到“RuntimeLibrary”的不匹配项: 值“MTd_StaticDebug”不匹配值“MDd_DynamicDebug”(main.obj 中)

msvcprtd.lib(MSVCP140D.dll):-1: error: LNK2005: "public: struct _Cvtvec __thiscall std::_Locinfo::_Getcvt(void)const " (?_Getcvt@_Locinfo@std@@QBE?AU_Cvtvec@@XZ) 已经在 libbitcoin.lib(checkpoint.obj) 中定义

I also tried to use the options below in Qt but no luck:
#QMAKE_CFLAGS_DEBUG += -MTd
#QMAKE_CXXFLAGS_DEBUG += -MTd

Also I tried to build the libbitcoin.lib with /MDd, no luck neither.
The Qt kit is:
![image](https://user-images.githubusercontent.com/8342412/39223478-e8445d06-4874-11e8-977b-d82b885d089d.png)

**Comment by evoskuil** [comment]
You appear to be attempting to link the static libs to Qt while telling Qt you are linking dynamic libs (dlls). MTd is multithreaded dynamic and MDd is multithreaded debug dynamic. The Libbitcoin libs do not build as DLLs in VS, so you must link them statically to Qt and tell Qt to use the static C runtime. There is some related info [here](https://stackoverflow.com/questions/14932315/how-to-compile-qt-5-under-windows-or-linux-32-or-64-bit-static-or-dynamic-on-v).

**Comment by GingerMoon** [comment]
@evoskuil 
I tried to build libbitcoin.lib with the option /MDd (it's still a lib, not DLL) and use it in Qt, finally no compile error or link error, but when I run the application, I met an run time error. 
![image](https://user-images.githubusercontent.com/8342412/39310708-b1d35ee6-499d-11e8-9f83-bec820ffb193.png)

So would you please confirm if the option /MD is supported for libbiticoin.lib? If no, would you please share the reason why we don't support the build option /MD?

**Comment by evoskuil** [comment]
When you create a dynamic library it is a DLL. A stub import LIB is also created, so that the DLL can be linked.

The DLL builds are not supported because the exported function signatures are too complex. I haven't looked at this since VS2013 however.

**Comment by GingerMoon** [comment]
Hi @evoskuil 
Thank you for your reply. I knew the concept of dll and lib.
What I want to know is, there are two options of building a lib, [/MD and /MT](https://msdn.microsoft.com/en-us/library/2kzt1wy3.aspx).
Is it support to build the libbitcoin.lib with the option of /MD instead of /MT?

**Comment by evoskuil** [comment]
Yes, but that only enables debug symbols (for the static lib).
