### ISSUE TITLE
Does libbitcoin provide TRNG?

### ISSUE THREAD

**Issue by GingerMoon** [libbitcoin/libbitcoin#940]
@evoskuil 
libbitcoin provide pseudo_random in random.cpp, however, it's not safe because it is much easier to generate two same random numbers than using TRNG, am I right?
Does libbitcoin provide TRNG?

Best Regards,

**Comment by thecodefactory** [comment]
@GingerMoon No, libbitcoin provides pseudo_random only, although nothing depends on it cryptographically.  Everywhere it matters, your own random data must be provided.

**Comment by evoskuil** [comment]
Technically it depends on the underlying OS RNG, but we assume that is not a TRNG.
