### ISSUE TITLE
libbitcoin library build error on linux

### ISSUE THREAD

**Issue by crypto-skywarp** [libbitcoin/libbitcoin#943]
Hello!

I got latest from github repo from https://github.com/libbitcoin/libbitcoin

Already built https://github.com/libbitcoin/secp256k1

However, this build error seems to indicate that the two repos HEADs are out of sync.

  ...
  CXX      src/wallet/parse_encrypted_keys/src_libbitcoin_la-parse_encrypted_private.lo
  CXX      src/wallet/parse_encrypted_keys/src_libbitcoin_la-parse_encrypted_public.lo
  CXX      src/wallet/parse_encrypted_keys/src_libbitcoin_la-parse_encrypted_token.lo
  CXXLD    src/libbitcoin.la
copying selected object files to avoid basename conflicts...
  CXX      examples/examples_libbitcoin_examples-main.o
  CXXLD    examples/libbitcoin_examples
src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recover'
src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_sign_recoverable'
src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recoverable_signature_serialize_compact'
src/.libs/libbitcoin.so: undefined reference to `secp256k1_ecdsa_recoverable_signature_parse_compact'
collect2: error: ld returned 1 exit status
make: *** [Makefile:2185: examples/libbitcoin_examples] Error 1

Also, running git tag on secp256k1 does not return anything, so it is impossible to figure out what commit on secp256k1 is compatible with what commit on libbitcoin.

Any help appreciated!

**Comment by thecodefactory** [comment]
Please trying running the install.sh script, which takes care of retrieving and installing all required dependencies.  For example: https://github.com/libbitcoin/libbitcoin/blob/version3/README.md#building-icu-zlib-png-qrencode-andor-boost

Once you have that working and understand what it's doing, then building repos separately becomes easier.

**Comment by thecodefactory** [comment]
Depends on what you're trying to do.  The production/stable version is latest version3 tag right now, so that's recommended for using the system as intended.  New developments for the upcoming version4 is HEAD of master, so pretty much exclusively for developers.

**Comment by crypto-skywarp** [comment]
Thank you! Issue closed.

**Comment by evoskuil** [comment]
The reason for the original libsecp error was not a dependency mismatch but a missing g flag on the libsecp build (see readme).
