### ISSUE TITLE
How to encrypt the private key with the wallet's password?

### ISSUE THREAD

**Issue by GingerMoon** [libbitcoin/libbitcoin#944]
Hi @evoskuil , 
I am developing a wallet, which is similar to electrum (with mnemonics).
Some of the features are below:
1. The private key is encrypted by the wallet password.
2. User can change the wallet password. In order to do this, the user need to input old password and new password. Wallet will check whether the old password is correct or not via:
Decrypt the private key with the old password to get the private_key1. Generate public_key1 via the private_key1. Check public_key1 with the public_key which is stored on the disk without being encrypted.
If public_key1 is the same as public_key, then the old password is correct. Then using the new password to encrypt the private key.

Is there any sample code or recommended way to accomplishing the features related to the wallet password?

Below are what I tried:
ec_secret is supported by encrypt and decrypt, however, it cannot be used to construct hd_private.
(Is it because maybe some information can be lost?)

My wallet doesn't have to provide HD feature. So I can use ec_private too. However, I don't find the API to construct ec_private via mnemonics.  The only way I can find is, using mnemonics to construct hd_private, and then using hd_private.ec_secret to construct ec_private.

encrypted_private is supported by create_key_pair(...encrypted_token...), however, I don't find the method of constructing encrypted_token using the mnemonics.

I also checked the documents:
https://github.com/libbitcoin/libbitcoin/wiki/Examples-from-Addresses-and-HD-Wallets
https://github.com/libbitcoin/libbitcoin/wiki/Addresses-and-HD-Wallets

By the way, why is there electrum and electrum_dictionary files? Is there any relation ship between libbitcoin and electrum?
I also checked the source code of electurm, below is the code snip of checking password:
    def check_password(self, password):
        xprv = pw_decode(self.xprv, password)
        if deserialize_xprv(xprv)[4] != deserialize_xpub(self.xpub)[4]:
            raise InvalidPassword()

the [4] element is actually the c below:
c = xkey[13:13+32]

Any insight would be much appreciated!

**Comment by evoskuil** [comment]
> ec_secret is supported by encrypt and decrypt, however, it cannot be used to construct hd_private.
(Is it because maybe some information can be lost?)

It is because hd_private requires a related secret and chain code. Providing ec_secret alone is insufficient without the chain code.

**Comment by evoskuil** [comment]
> However, I don't find the API to construct ec_private via mnemonics.

A BIP39 mnemonic accepts a seed (entropy) and returns a word list. The word list can be combined with a passphrase to emit a wallet seed. The wallet seed can be used to generate your `ec_secret`/`ec_private` or may be passed through `hd_private` to do so. An `ec_secret` is any random number that passes `bc::verify(const ec_secret& secret)`.

**Comment by evoskuil** [comment]
> Is there any relation ship between libbitcoin and electrum?

libbitcoin-explorer supports Electrum mnemonic commands and libbitcoin-server will eventually provide Electrum client-server semantics.

**Comment by evoskuil** [comment]
> Any insight would be much appreciated!

@thecodefactory ?

**Comment by thecodefactory** [comment]
See my comment here about converting seeds to key pairs:

https://github.com/libbitcoin/libbitcoin/issues/928

**Comment by thecodefactory** [comment]
Sorry, closed by accident.

**Comment by GingerMoon** [comment]
Hi guys,
Thank you very much for your replies.
I'd like to try to encrypt/decrypt ec_secret. I am writing the following code to construct es_secret:
    long_hash hd_seed = decode_mnemonic(words);
    data_chunk seed_chunk(to_chunk(hd_seed));
    hd_private m(seed_chunk, hd_private::mainnet);
    ec_secret secret = m.secret();

Would you please tell me if it is possible to provide new API to construct es_secret via mnemonics?
Or has there already been any existing API?

**Comment by thecodefactory** [comment]
I'm not sure what you're asking for.  There is no direct mnemonic to ec_secret conversion because a mnemonic is not a direct encoding of an ec_secret (non-HD private key).  Ordinarily, you would translate the mnemonic to the seed which is commonly used for an HD private key.  But an HD private key is not just an ec_secret either, it's a means to derive additional keys via [BIP32.](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)  That said, you could do it the way you've shown if you'd like.

**Comment by evoskuil** [comment]
You are unnecessarily creating a second copy of the seed chunk:
```cpp
auto seed = decode_mnemonic(words);
hd_private m(to_chunk(seed), hd_private::mainnet);
auto secret = m.secret();
```

**Comment by GingerMoon** [comment]
Thank you both very much!
