### ISSUE TITLE
Why is hd_private(ec_secret, chain_code, hd_lineage) private?

### ISSUE THREAD

**Issue by GingerMoon** [libbitcoin/libbitcoin#956]
Hi guys, 
May I know if there is any special reason why the constructor below is private?
hd_private(const ec_secret& secret, const hd_chain_code& chain_code,
        const hd_lineage& lineage);

1. I have a ec_secret and hd_public and want to construct a hd_private, is it possible?
2. I want to encrypt/decrypt hd_private. Is there any special reason why there is no such APIs?

**Comment by thecodefactory** [comment]
That constructor is private because it's only internally used and not an exposed API.

1) No, I don't think that makes sense.  An hd_private is not a pair of ec_secret and hd_public.

2) There is no _standard_ way to encrypt an hd_private.  You could encrypt either the encoded version, or the binary seed instead.

**Comment by GingerMoon** [comment]
Hi @thecodefactory and @evoskuil 
Thank you both very much for answering my questions.

1. "That constructor is private because it's only internally used and not an exposed API."
May I know why this constructor is only internally used? Can it be changed to public?

2. "You could encrypt either the encoded version, or the binary seed instead."
I was not able to find a suitable pair of encrypt/decrypt APIs under the path libbitcoin/src/wallet.
Should I use the APIs under the path libbitcoin/src/math?
Would you please recommend me some APIs?

3. hd_private inherits hd_public, and contains only one field ec_secret.
That's why I think it is possible to construct hd_private via hd_public and ec_secret.
More insight into it would be appreciated.

Best Regards,

**Comment by thecodefactory** [comment]
1) Do you have a need to use it/can you show a case where it's needed?

2) Libbitcoin is not a general encryption library, so "encrypt/decrypt" methods are not needed without a specific context.  I would think a more general cryptography library should be considered.  There are some aes256 methods used for BIP38, which may or may not be suitable for your uses: https://github.com/libbitcoin/libbitcoin/blob/master/include/bitcoin/bitcoin/math/crypto.hpp#L44

3) Ok. I'm no expert there.

**Comment by evoskuil** [comment]
It’s used privately to reduce code complexity. It’s not public because it’s unsafe. An ec public key is derived from an ec private key. Exposing both to construction is unnecessary and confusing, and would require validation of the relationship.

**Comment by GingerMoon** [comment]
Thank you both for sharing your insights!

regards,

**Comment by thecodefactory** [comment]
Closed due to inactivity.
