### ISSUE TITLE
ring_signature tests require c++14

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin#959]
Hi @narodnik - the VC++ 2013/15/17 project files did not include the additional sources or tests and as such the break (named parameters require c++14) was not detected in AppVeyor, but it is a break. The generated `ring_signature` tests will need to change to resolve this break.

Also, I see no reason to have any more than one of these tests. The space is practically infinite - so the benefit of multiple randomly-generated tests is essentially zero more than a single test. As such I intend to resolve the above issue by creating a single literal test from the first vector.

**Comment by narodnik** [comment]
ok, as you prefer. I simply copied the unit tests from secp256k1-zkp which generates several random unit test vectors.

**Comment by evoskuil** [comment]
https://github.com/libbitcoin/libbitcoin/pull/960
