### ISSUE TITLE
Why is this so difficult to build/install?

### ISSUE THREAD

**Issue by odonnellnoel** [libbitcoin/libbitcoin#968]
Please invest some time in fixing builds, thx

**Comment by evoskuil** [comment]
Specifics please.

All builds for all repos and all supported platforms are generated, trivial to run and tested in CI on every commit.

**Comment by odonnellnoel** [comment]
I finally got it building - I made the mistake of trying to us the configure/make/make install, when all I needed was the install.sh.

Thanks

**Comment by evoskuil** [comment]
The libsecp256k1 issue is a consequence of the maintainers not re-versioning the library when the public interface changes.
