### ISSUE TITLE
ZMQ notices just for wallet-affecting TXes?

### ISSUE THREAD

**Issue by Crypto2** [libbitcoin/libbitcoin#970]
Maybe this exists and didn't see it in the docs but is there a way to get txhash ZMQ notices just for wallet-affecting TXes?

If not I guess this is a feature request. I saw a request for JSON-encoded ZMQ notices that was shot down that was pretty good with the official answer being to decode the raw TX or use RPC, I think this would be great for the latter since it would cut down on the number of RPC calls greatly.

**Comment by evoskuil** [comment]
To subscribe to address notifications use the following client-server interface message: https://github.com/libbitcoin/libbitcoin-server/wiki/Query-Service#subscribeaddress

I don’t follow your other comments, but the notification identifies the tx, which you can then request and of course need to be able to deserialze. The libbitcoin-client library provides call wrappers with deserialization code for c++ callers.

**Comment by Crypto2** [comment]
Not sure that would work well having to sub every address individually, we have over 5 million addresses.

**Comment by Crypto2** [comment]
Ooops, my bad. I just noticed I posted this in the wrong tab. Meant to post in in bitcoin vs libbitcoin.

**Comment by evoskuil** [comment]
Well then I take back my comments on performance and scalability ;).
