### ISSUE TITLE
Excessive gcov warnings.

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin#986]
https://travis-ci.org/libbitcoin/libbitcoin/jobs/402343113

**Comment by pmienk** [comment]
Addressed in master by libbitcoin/libbitcoin-build#171 and version3 by libbitcoin/libbitcoin-build#172 and the resulting artifact regeneration pull requests now pending.

**Comment by evoskuil** [comment]
Resolved.
